<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\ConfigurableProduct\Block\Product\View\Type\Configurable;
use Magento\Framework\Escaper;

/** @var Configurable $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */

$product = $block->getProduct();
$productId = $product->getId();
$attributes = $block->decorateArray($block->getAllowAttributes());
$jsonConfig = $block->getJsonConfig();
?>
<?php if ($product->isSaleable() && count($attributes)): ?>
    <script>
        function initConfigurableDropdownOptions() {
            const { productId } = this.$root.dataset;
            const configEl = this.$root.querySelector('script[type="application/json"]');

            return initConfigurableOptions(productId, JSON.parse(configEl.textContent));
        }

        window.addEventListener('alpine:init', () => {
            Alpine.data('initConfigurableDropdownOptions', initConfigurableDropdownOptions)
        }, { once: true });
    </script>
    <?php $hyvaCsp->registerInlineScript() ?>

    <div
        x-data="initConfigurableDropdownOptions"
        data-product-id="<?= (int) $productId ?>"
        class="mb-6"
    >
        <script type="application/json"><?= /* @noEscape */ str_replace('</script>', '<\/script>', $jsonConfig) ?></script>

        <?php foreach ($attributes as $attribute): ?>
            <?php
            $attributeId = $attribute->getAttributeId();
            $productOptions = $attribute->getOptions();
            ?>
            <div class="flex w-full flex-col items-center border-t border-gray-300 py-4 sm:items-start sm:py-2 last:border-b">
                <label
                    class="w-full text-start text-gray-700 label sm:w-1/2"
                    for="attribute<?= $escaper->escapeHtmlAttr($attributeId) ?>"
                >
                    <?= $escaper->escapeHtml($attribute->getProductAttribute()->getStoreLabel()) ?>
                </label>
                <div class="w-full text-start text-gray-900 sm:ms-2 sm:w-1/2">
                    <select
                        id="attribute<?= $escaper->escapeHtmlAttr($attributeId) ?>"
                        name="super_attribute[<?= $escaper->escapeHtmlAttr($attributeId) ?>]"
                        class="form-select super-attribute-select w-full max-w-full"
                        required
                        data-attribute-id="<?= $escaper->escapeHtmlAttr($attributeId) ?>"
                        @change="reflectOption"
                    >
                        <option value=""><?= $escaper->escapeHtml(__('Choose an Option...')) ?></option>
                        <?php foreach ($productOptions ?? [] as $option): ?>
                            <option
                                value="<?= $escaper->escapeHtmlAttr($option['value_index']) ?>"
                                data-attribute-id="<?= $escaper->escapeHtmlAttr($attributeId) ?>"
                                data-option-label="<?= $escaper->escapeHtmlAttr($option['store_label']) ?>"
                                :disabled="optionIsDisabled"
                                x-text="getOptionLabel"
                            ><?= $escaper->escapeHtml($option['store_label']) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
