<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\Cart\Items as CartItems;
use Hyva\Theme\ViewModel\ProductList;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\Store;
use Magento\Catalog\Block\Product\ReviewRendererInterface as ProductReviewRenderer;
use Magento\Catalog\Model\Product\Visibility as ProductVisibility;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

/** @var ProductList $productListViewModel */
$productListViewModel = $viewModels->require(ProductList::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

/** @var Store $storeViewModel */
$storeViewModel = $viewModels->require(Store::class);

$sliderName = $block->getSliderName() ?: str_replace(['.', '/', '\\'], '_', $block->getNameInLayout());
$title = $block->getTitle() ?: '';
$headingTag = $block->getHeadingTag() ?: 'h3';
$cssClasses = $block->getCssClasses() ?: 'product-slider lg:mb-[13px] body-font';
$headingCssClasses = $block->getHeadingCssClasses() ?: 'text-xl lg:text-3xl font-bold text-[#1d2024] title-font text-center';

$columnCount = $block->getColumnCount() ?? 4;
$sliderClasses = implode(' ', array_filter([
        'swiper-wrapper',
        'mx-auto',
        'grid',
        'gap-4',
        'sm:grid-cols-2',
        'lg:grid-cols-4',
        'relative',
        'overflow-y-hidden',
        'overflow-x-scroll',
        $block->getSliderCssClasses()
]));

$showHeading = $block->getShowHeading() ?? true;
$hideDetails = $block->getHideDetails() ?? false;
$hideRatingSummary = $block->getHideRatingSummary() ?? false;

// Filter Options
$pageSize = $block->getPageSize() ?: 8;
$skusFilter = $block->getProductSkus() ? explode(',', $block->getProductSkus()) : [];
$additionalFilters = $block->getAdditionalFilters() ?: [];

$sortAttribute = $block->getSortAttribute() ?: '';
$sortDirection = $block->getSortDirection() ?: 'ASC';

$type = $block->getType();
// In case $type is not set on the block, it will default the block class name, which is not what we need in this template.
$type = is_string($type) && strpos($type, '\\') === false ? $type : 'generic';

if ($hideRatingSummary) {
    $productListViewModel->excludeReviewSummary();
}

if ($categoryIds = $block->getCategoryIds()) {
    $productListViewModel->addFilter('category_id', $categoryIds, 'in');
}

if ($isAnchorCategory = $block->getIncludeChildCategoryProducts()) {
    // Only has an effect if a single category ID filter is set, and that category is an anchor category
    $productListViewModel->includeChildCategoryProducts();
}

if ($priceFrom = $block->getPriceFrom()) {
    $productListViewModel->addFilter('price', $priceFrom, 'gteq');
}

if ($priceTo = $block->getPriceTo()) {
    $productListViewModel->addFilter('price', $priceTo, 'lteq');
}

if ($skusFilter) {
    $productListViewModel->addFilter('sku', array_map('trim', $skusFilter), 'in');
}

if (is_string($additionalFilters)) {
    $additionalFilters = json_decode($additionalFilters, true);
}

if (is_array($additionalFilters)) {
    foreach ($additionalFilters as $filter) {
        $productListViewModel->addFilter($filter['field'], $filter['value'], $filter['conditionType'] ?? 'eq');
    }
}

$productListViewModel->setPageSize($pageSize);
$productListViewModel->addFilter('website_id', $storeViewModel->getWebsiteId());
$productListViewModel->addFilter('visibility', [ProductVisibility::VISIBILITY_IN_CATALOG, ProductVisibility::VISIBILITY_BOTH,], 'in');

if ($sortAttribute) {
    $sortDirection === 'ASC'
            ? $productListViewModel->addAscendingSortOrder($sortAttribute)
            : $productListViewModel->addDescendingSortOrder($sortAttribute);
}

if (in_array($type, ['related', 'upsell', 'crosssell'], true)) {
    $items = $type === 'crosssell'
            ? $productListViewModel->getCrosssellItems(...$viewModels->require(CartItems::class)->getCartItems())
            : $productListViewModel->getLinkedItems($type, $block->getProduct());
} else {
    $items = $productListViewModel->getItems();
}

if (!$items) {
    return '';
}

$itemRenderer = $block->getLayout()->getBlock('product_list_item')
        ?: $block->getChildBlock('slider.item.template')
                ?: $block->getLayout()->createBlock(Template::class);

$itemRenderer->setData('hide_details', $hideDetails);

$sliderConfig = [
        'autoplay' => 'true',
        'autoplaySpeed' => 3000,
        'infiniteLoop' => 'false',
        'showArrows' => 'true',
        'showDots' => 'false',
];
?>

<script>
    'use strict';

    function initSliderComponent() {
        return {
            getTextDirection: function () {
                return document.querySelector('html').dir || 'ltr';
            }
        }
    }
</script>

<section
        id="<?= $escaper->escapeHtmlAttr($sliderName) ?>"
        class="<?= $escaper->escapeHtmlAttr($cssClasses) ?>"
        aria-label="<?= $escaper->escapeHtmlAttr($title); ?>"
        data-slider-type="<?= $escaper->escapeHtmlAttr($type) ?>"
        x-data="initSliderComponent()"
        x-defer="intersect"
>
    <a
            href="#<?= $escaper->escapeHtmlAttr($sliderName) ?>-slider-end"
            class="action skip sr-only focus:not-sr-only focus:absolute focus:z-30 focus:bg-white"
    ><?= $escaper->escapeHtml(__('Press to skip carousel')) ?></a>

    <div
            class="relative"
            data-content-type="products-slider"
            data-autoplay="<?= $escaper->escapeHtmlAttr($sliderConfig['autoplay']) ?>"
            data-autoplay-speed="<?= (int)$sliderConfig['autoplaySpeed'] ?>"
            data-infinite-loop="<?= $escaper->escapeHtmlAttr($sliderConfig['infiniteLoop']) ?>"
            data-show-arrows="<?= $escaper->escapeHtmlAttr($sliderConfig['showArrows']) ?>"
            data-show-dots="<?= $escaper->escapeHtmlAttr($sliderConfig['showDots']) ?>"
    >
        <div class="container flex flex-col items-center justify-between gap-2 max-md:pt-[22px] pt-5 md:pb-3 mx-auto mb-[15px] md:flex-row">
            <?php if ($showHeading && $title): ?>
                <?= $escaper->escapeHtml(str_replace(
                        ['%1', '%2', '%3'],
                        [$headingTag, $title, $headingCssClasses],
                        '<%1 class="%3">%2</%1>'
                ), ['h1', 'h2', 'h3', 'h4', 'h5', 'h6']) ?>
            <?php endif; ?>
        </div>

        <div class="swiper product-items" :dir="getTextDirection()">
            <div class="<?= $escaper->escapeHtmlAttr($sliderClasses) ?>">
                <?php foreach ($items as $product): ?>
                    <div class="swiper-slide flex flex-col h-auto" role="tabpanel">
                        <?= /** @noEscape */
                        $productListItemViewModel->getItemHtmlWithRenderer(
                                $itemRenderer,
                                $product,
                                $block,
                                'grid',
                                ProductReviewRenderer::SHORT_VIEW,
                                'category_page_grid',
                                false
                        ) ?>
                    </div>
                <?php endforeach; ?>
            </div>

            <div class="carousel-nav">
                <?php if ($sliderConfig['showDots'] === 'true'): ?>
                    <div class="swiper-pagination invisible"></div>
                <?php endif; ?>
                <?php if ($sliderConfig['showArrows'] === 'true'): ?>
                    <div class="swiper-button-prev invisible">
                        <?= $lucideIcons->renderHtml('chevron-right', '', 24, 24, ['aria-hidden' => 'true']) ?>
                    </div>
                    <div class="swiper-button-next invisible">
                        <?= $lucideIcons->renderHtml('chevron-left', '', 24, 24, ['aria-hidden' => 'true']) ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <span id="<?= $escaper->escapeHtmlAttr($sliderName) ?>-slider-end" tabindex="-1"></span>
    </div>
</section>
