<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Store;
use Magento\Catalog\Block\Product\ReviewRendererInterface as ProductReviewRenderer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

$viewMode = 'grid';
$imageDisplayArea = 'category_page_grid';
$showDescription = false;

$name = (string) $block->getName();
$title = (string) $block->getTitle();
$headingTag = $block->getData('heading_tag') ?: 'h3';
$items = $block->getItems() ?? [];
if (is_object($items) && $items instanceof Iterator) {
    $items = iterator_to_array($items);
}
if (!$itemCount = count($items)) {
    return '';
}

$sliderIndex = 1;
$sliderItemRenderer = $block->getLayout()->getBlock('product_list_item')
    ?: $block->getChildBlock('slider.item.template')
    ?: $block->getLayout()->createBlock(Template::class);

$hideRatingSummary = (bool) $block->getData('hide_rating_summary');
$hideDetails       = (bool) $block->getData('hide_details');

$sliderItemRenderer->setData('hide_details', $hideDetails);
$sliderItemRenderer->setData('hide_rating_summary', $hideRatingSummary);

// The slider item renderer block is often a shared instance.
// If a specific item template is set for this slider, the previously set template must be reset later
// so the item template is only replaced for the one slider it is specified on.
$sharedItemRendererTemplate = null;
$isSharedItemRenderer       = $sliderItemRenderer !== $block->getChildBlock('slider.item.template');
if ($isSharedItemRenderer && $block->getChildBlock('slider.item.template')) {
    $sharedItemRendererTemplate = $sliderItemRenderer->getTemplate();
    $sliderSpecificItemTemplate = $block->getChildBlock('slider.item.template')->getTemplate();
    $sliderItemRenderer->setTemplate($sliderSpecificItemTemplate);
}

// The number of slides visible on the xl breakpoint
$maxVisibleSlides = $block->getData('max_visible') ?? 4;

// Breakpoints for 1 visible slider items on mobile, 2 visible on md, 3 on lg and 4 on xl (see $sliderPageSize).
$defaultSliderItemClasses = 'swiper-slide flex flex-col h-auto';

$sliderSectionClasses = $block->getData('maybe_purged_tailwind_section_classes') ?? 'lg:mb-[13px] text-gray-700 body-font';
$slideItemClasses = $block->getData('maybe_purged_tailwind_slide_item_classes') ?? $defaultSliderItemClasses;

$sliderConfig = [
    'autoplay' => 'true',
    'autoplaySpeed' => 3000,
    'infiniteLoop' => 'false',
    'showArrows' => 'true',
    'showDots' => 'false'
];
?>
<script>
    'use strict';

    function initSliderComponent() {
        return {
            getTextDirection: function () {
                return document.querySelector('html').dir || 'ltr';
            }
        }
    }
</script>
<section
    class="<?= $escaper->escapeHtmlAttr($sliderSectionClasses) ?>"
    x-data="initSliderComponent()"
    x-id="['slider-nav', 'slider-desc', 'slider-id']"
    role="group"
    aria-roledescription="<?= $escaper->escapeHtmlAttr(__('Carousel')) ?>"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Carousel %1', $title)) ?>"
    :aria-describedby="$id('slider-desc')"
    x-defer="intersect"
>
    <?php if ($items): ?>
        <div class="relative" data-content-type="products-slider"
             data-autoplay="<?= $sliderConfig['autoplay'] ?>"
             data-autoplay-speed="<?= $sliderConfig['autoplaySpeed'] ?>"
             data-infinite-loop="<?= $sliderConfig['infiniteLoop'] ?>"
             data-show-arrows="<?= $sliderConfig['showArrows'] ?>"
             data-show-dots="<?= $sliderConfig['showDots'] ?>"
        >
            <?php if ($title): ?>
                <div class="container flex flex-col items-center justify-between max-md:pt-[22px] pt-5 md:pb-3 mx-auto mb-[15px] md:flex-row">
                    <<?= /* @noEscape */ $headingTag ?> class="text-xl lg:text-3xl font-bold text-[#1d2024] title-font text-center">
                        <?= $escaper->escapeHtml($title); ?>
                    </<?= /* @noEscape */ $headingTag ?>>
                </div>
            <?php endif; ?>
            <a
                href="#<?= $escaper->escapeHtmlAttr($name) ?>-slider-end"
                class="action skip sr-only focus:not-sr-only focus:absolute focus:z-30 focus:bg-white"
            >
                <?= $escaper->escapeHtml(__('Press to skip carousel')) ?>
            </a>
            <div class="swiper product-items" :dir="getTextDirection()">
                <div class="swiper-wrapper mx-auto grid gap-4 sm:grid-cols-2 lg:grid-cols-4 relative overflow-y-hidden overflow-x-scroll">
                    <?php foreach ($items as $product): ?>
                        <div class="<?= $escaper->escapeHtmlAttr($slideItemClasses) ?>">
                            <?= /** @noEscape */ $productListItemViewModel->getItemHtmlWithRenderer(
                                $sliderItemRenderer,
                                $product,
                                $block,
                                $viewMode,
                                ProductReviewRenderer::SHORT_VIEW,
                                $imageDisplayArea,
                                $showDescription
                            ) ?>
                        </div>
                    <?php endforeach; ?>
                </div>
                <div class="carousel-nav">
                    <div class="swiper-pagination invisible"></div>
                    <div class="swiper-button-prev invisible">
                        <?= $lucideIcons->renderHtml('chevron-right', '', 24, 24, ['aria-hidden' => 'true']) ?>
                    </div>
                    <div class="swiper-button-next invisible">
                        <?= $lucideIcons->renderHtml('chevron-left', '', 24, 24, ['aria-hidden' => 'true']) ?>
                    </div>
                </div>
            </div>
            <span id="<?= $escaper->escapeHtmlAttr($name) ?>-slider-end" tabindex="-1"></span>
        </div>
    <?php endif; ?>
</section>
<?php

if ($sharedItemRendererTemplate) {
    $sliderItemRenderer->setTemplate($sharedItemRendererTemplate);
}

?>
