<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Customer\Block\Widget\Taxvat;
use Magento\Customer\Helper\Address as AddressHelper;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Taxvat $block */
?>
<div class="field field-reserved floating-labels taxvat <?= $block->isRequired() ? 'required' : ''; ?> mb-8 w-full">
    <div class="control">
        <input type="text"
               id="otp_<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')) ?>"
               name="<?= $escaper->escapeHtmlAttr($block->getFieldName('taxvat')) ?>"
               value="<?= $escaper->escapeHtmlAttr($block->getTaxvat()) ?>"
               title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('taxvat')) ?>"
               placeholder=" "
               class="form-input peer w-full <?= $escaper->escapeHtmlAttr($this->helper(AddressHelper::class)->getAttributeValidationClass('taxvat')) ?>"
               @keydown.enter.prevent="submitForm($el.form);"
               x-model.fill="taxvat"
               x-ref="taxvat"
            <?= $block->isRequired() ? ' :required="isStep(\'registration\')"' : '' ?>
        >
        <label class="label floating-labels-label"
               for="<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')) ?>">
            <?= $escaper->escapeHtml($block->getStoreLabel('taxvat')) ?>
        </label>
    </div>
</div>
