<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */

?>
<?php if (!$block->hasError()): ?>
    <?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
    <nav class="max-md:fixed max-md:bottom-0 max-md:inset-x-0 max-md:w-full max-md:z-[29] max-md:p-2.5 max-md:bg-white max-md:shadow-[0_-2px_4px_0_rgba(0,0,0,0.06)]" aria-label="<?= $escaper->escapeHtmlAttr(__('Go to Checkout')) ?>">
        <ul class="checkout methods items checkout-methods-items space-y-2">
            <?php foreach ($methods as $method): ?>
                <?php $methodHtml = $block->getMethodHtml($method); ?>
                <?php if (trim($methodHtml) !== ''): ?>
                    <li class="item"><?= /* @noEscape */ $methodHtml ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </nav>
<?php endif; ?>
