<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>

<div class="w-full flex flex-wrap gap-y-10 items-start px-4 xl:px-0 clearfix">
    <div class="xl:w-1/4 order-2 grow -mx-4 sm:mx-0 px-4 py-6 md:px-6 md:rounded-2xl bg-zinc-50">
        <h2 class="w-full mb-7 md:mb-11 text-2xl leading-8 font-bold">
            <?= $escaper->escapeHtml(__('Cart Summary')) ?>
        </h2>
        <?= $block->getChildHtml('cart.summary') ?>
    </div>
    <div class="w-full xl:w-3/4 order-1 xl:pe-8">
        <?= $block->getChildHtml('form_before') ?>
        <?= $block->getChildHtml('cart-items') ?>
        <?= $block->getChildHtml('checkout_cart_widget') ?>
    </div>
</div>
