<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

// phpcs:disable Generic.WhiteSpace.ScopeIndent
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductStockItem;
use Magento\Checkout\Block\Cart\Item\Renderer;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\SvgIcons;
use SR\HyvaProductQtySpinner\ViewModel\ProductQtySpinner;

/** @var Renderer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ProductStockItem $stockItemViewModel */
/** @var LucideIcons $lucideIcons */
/** @var SvgIcons $icons */
/** @var ProductQtySpinner $productQtySpinner */

$stockItemViewModel = $viewModels->require(ProductStockItem::class);

$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();

$minSalesQty = $stockItemViewModel->getMinSaleQty($product);
$maxSalesQty = $stockItemViewModel->getMaxSaleQty($product);
$qty = $stockItemViewModel->isQtyDecimal($product)
    ? $block->getQty()
    : (int) $block->getQty();

$step = $stockItemViewModel->getQtyIncrements($product)
    ? $stockItemViewModel->getQtyIncrements($product)
    : null;

/**
 * sets minimum and maximum values taking into account the values set in the admin,
 * but taking into account the value of Qty Increments
 */
if ($step) {
    $minSalesQty = ceil($minSalesQty / $step) * $step;
    $maxSalesQty = floor($maxSalesQty / $step) * $step;
    $qty = ceil($qty / $step) * $step;
}

$maxSalesQtyLength = ($maxSalesQty ? strlen((string) $maxSalesQty) : 4)
    + (/* add one if decimal for separator */ (int) $stockItemViewModel->isQtyDecimal($product));

$icons = $viewModels->require(SvgIcons::class);
$lucideIcons = $viewModels->require(LucideIcons::class);
$productQtySpinner = $viewModels->require(ProductQtySpinner::class)->setProduct($product);
$productMaxQty = $productQtySpinner->getMaxQty();
$productMinQty = $productQtySpinner->getMinQty();
$productQtyIncrements = $productQtySpinner->getQtyIncrements();
$productQtyConfig = [
    'maxQty' => $productMaxQty ?: null,
    'minQty' => $productMinQty ?: null,
    'qtyIncrements' => $productQtyIncrements ?: null,
];
$hasError = !empty(array_filter(
    $block->getMessages(),
    fn($item) => ($item['type'] ?? null) === 'error'
));
$rowCss = 'sm:py-5 sm:px-2 xl:px-4 sm:table-cell';
$imageCss = 'product-item-photo shrink-0 !absolute sm:!static start-3 top-6 sm:max-w-16 ' . ($hasError ? 'opacity-40' : '');
?>
<tbody class="cart item relative border-b border-gray-300 last:border-0"
    <?php foreach ($block->getData('cart_item_data_attributes') ?? [] as $attribute => $include): ?>
        <?php if ($include): ?>
            <?php /** Append data-* attributes based on layout XML arguments */ ?>
            <?= $escaper->escapeHtml(sprintf('data-%s', $attribute)); ?>="<?= $escaper->escapeHtmlAttr($item->getData($attribute)); ?>"
        <?php endif; ?>
    <?php endforeach; ?>
>
    <tr class="item-info flex flex-col gap-4 sm:table-row min-h-[96px] sm:min-h-0 ps-[120px] py-6 px-3 sm:p-0 <?= $hasError ? 'bg-gray-50': '' ?>">
        <td data-th="<?= $escaper->escapeHtml(__('Item')) ?>"
            class="col item <?= $rowCss ?> sm:ps-4 xl:ps-8">
            <div class="sm:flex sm:gap-2 xl:gap-4">
                <?php if ($block->hasProductUrl()): ?>
                <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
                   tabindex="-1"
                   class="<?= $imageCss ?>">
                    <?php else: ?>
                    <span class="<?= $imageCss ?>">
                <?php endif;?>
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')
                    ->setTemplate('Magento_Catalog::product/image.phtml')
                    ->toHtml() ?>
                <?php if ($block->hasProductUrl()): ?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
                <div class="product-item-details grow flex flex-col items-start gap-4 sm:gap-3">
                    <strong class="product-item-name break-all sm:py-2 text-lg leading-7 font-bold">
                        <?php if ($block->hasProductUrl()): ?>
                            <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
                               class="hover:text-primary">
                                <?= $escaper->escapeHtml($block->getProductName()) ?>
                            </a>
                        <?php else: ?>
                            <?= $escaper->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                    </strong>
                    <?php if ($messages = $block->getMessages()): ?>
                        <?php foreach ($messages as $message): ?>
                            <div class= "cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>">
                                <div><?= $escaper->escapeHtml($message['text']) ?></div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php if ($options = $block->getOptionList()): ?>
                        <dl class="item-options w-full break-all text-sm clearfix">
                            <?php foreach ($options as $option): ?>
                                <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                                <dt class="font-normal float-left clear-left me-2 mb-2"><?= $escaper->escapeHtml($option['label']) ?>:</dt>
                                <dd class="float-left">
                                    <?php if (isset($formatedOptionValue['full_view'])): ?>
                                        <?= $escaper->escapeHtml($formatedOptionValue['full_view']) ?>
                                    <?php else: ?>
                                        <?= $escaper->escapeHtml($formatedOptionValue['value'], ['span', 'a']) ?>
                                    <?php endif; ?>
                                </dd>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif;?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock): ?>
                        <?= $addInfoBlock->setItem($item)->toHtml() ?>
                    <?php endif;?>
                </div>
            </div>
        </td>

        <td class="col price flex items-center gap-2 <?= $rowCss ?> text-lg sm:text-xl">
                <span class="sm:hidden text-sm leading-5 font-normal">
                    <?= $escaper->escapeHtml(__('Price:')) ?>
                </span>
            <?= $block->getUnitPriceHtml($item) ?>
        </td>

        <td class="col qty <?= $rowCss ?> <?= $hasError ? 'opacity-40' : '' ?>">
            <label class="sr-only" for="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty">
                <?= $escaper->escapeHtml(__('Qty')) ?>
            </label>
            <div class="cart-qty-spinner max-w-[120px] me-auto relative flex flex-row sm:justify-end items-center justify-between overflow-hidden border border-gray-300 bg-white rounded-[14px] sm:rounded-[20px]"
                 x-data="initCartItemQtySpinner(<?= $escaper->escapeHtmlAttr($block->getQty()) ?>, <?= $escaper->escapeHtmlAttr($item->getId()) ?>, <?= htmlentities(json_encode($productQtyConfig)) ?>)">
                <?php
                $_buttonClass = 'h-[26px] px-2 flex shrink-0 grow justify-center items-center enabled:cursor-pointer outline-none hover:enabled:bg-gray-200 disabled:cursor-not-allowed';
                $_inputClass = 'no-spinner w-10 h-5 mx-1 p-0 rounded-md text-[13px] text-center text-black bg-gray-200 border-none shadow-none leading-none';
                ?>

                <button type="button"
                        data-action="decrement"
                        class="<?= $_buttonClass ?>"
                        :class="{
                                'disabled:cursor-not-allowed': isDecrementDisabled && !isRequestInProgress,
                                'disabled:cursor-wait': isRequestInProgress,
                            }"
                        @click="decrement()"
                    <?php if ($hasError): ?>
                        disabled
                    <?php else: ?>
                        :disabled="isDecrementDisabled()"
                    <?php endif ?>
                />
                <?= $lucideIcons->minusHtml('', 16, 16); ?>
                </button>

                <input data-role="cart-item-qty"
                       id="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty"
                       name="cart[<?= $escaper->escapeHtmlAttr($item->getId()) ?>][qty]"
                       type="number"
                       inputmode="decimal"
                       size="4"
                       title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                       class="<?= $_inputClass ?>"
                       min="0"
                       max="9999"
                       @blur="onBlur"
                       @keydown="onKeyDown"
                       @keydown.window.prevent.enter=""
                       @input.debounce.750="onInput"
                       :value="qty"
                    <?php if ($hasError): ?>
                        disabled
                    <?php else: ?>
                        :disabled="isDisabled"
                    <?php endif ?>
                       value="<?= $escaper->escapeHtmlAttr($qty) ?>"
                />

                <button type="button"
                        data-action="increment"
                        class="<?= $_buttonClass ?>"
                        :class="{
                                'disabled:cursor-not-allowed': isIncrementDisabled && !isRequestInProgress,
                                'disabled:cursor-wait': isRequestInProgress,
                            }"
                        @click="increment()"
                    <?php if ($hasError): ?>
                        disabled
                    <?php else: ?>
                        :disabled="isIncrementDisabled()"
                    <?php endif ?>
                />
                <?= $lucideIcons->plusHtml('', 16, 16); ?>
                </button>

                <div class="absolute inset-0 flex justify-center items-center text-primary-darker bg-white/75 shadow-[0_0_3px_2px_#fff]"
                     :class="{'invisible': !isDisabled}">
                    <?= $icons->spinnerHtml('h-full w-auto') ?>
                </div>
            </div>
        </td>

        <td class="col subtotal flex items-center gap-2 <?= $rowCss ?> text-lg sm:text-xl">
                <span class="sm:hidden text-sm leading-5 font-normal">
                    <?= $escaper->escapeHtml(__('Subtotal:')) ?>
                </span>
            <?= $block->getRowTotalHtml($item) ?>
        </td>

        <td class="col actions <?= $rowCss ?> absolute sm:static start-3 bottom-6 sm:w-[1%] p-2 sm:pr-4 xl:pe-8">
            <?= /* @noEscape */ $block->getActions($item) ?>
        </td>
    </tr>
</tbody>
