<?php
/**
 * @var \Magento\AdvancedSearch\Block\SearchData $block
 */
?>
<?php
/** @var \Magento\Search\Model\QueryResult[] $data */
$data = $block->getItems();
if (!$data) {
    return;
}
?>
<dl class="block mst-search__misc-recommendations mb-4">
    <dt class="inline-block mb-2 lg:mb-4 font-bold"><?= $block->escapeHtml(__($block->getTitle())) ?></dt>
    <?php foreach ($data as $additionalInfo) :
        $url = $block->escapeUrl($block->getLink($additionalInfo->getQueryText()));
        if (strripos($url, 'search_landing')!== false) {
            $url = str_replace('search_landing/page', 'catalogsearch/result', $url);
        }
        ?>
        <dd class="inline-block rounded-md px-3 py-1 bg-slate-100 text-slate-600">
            <a class="!no-underline" href="<?= $block->escapeUrl($url) ?>">
                <?= $block->escapeHtml($additionalInfo->getQueryText()) ?>
            </a>
            <?php if ($block->isShowResultsCount()) : ?>
                <span class="count"><?= (int)$additionalInfo->getResultsCount() ?></span>
            <?php endif; ?>
        </dd>
    <?php endforeach; ?>
</dl>
