<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var SvgIcons $icons */

$icons = $viewModels->require(SvgIcons::class);
?>
<div class="text-gray-600 text-base leading-6 bg-gray-100 relative">
    <?= $block->getChildHtml('newsletter') ?>

    <div class="bg-gray-100 lg:py-[32px]">
        <div class="container mx-auto px-7 pt-3 pb-2 lb:pt-0 lg:pb-0 lg:flex lg:justify-between">
            <?= $block->getChildHtml('menu-footer') ?>

            <div class="lg:mb-[32px] lg:order-last">
                <?= $block->getChildHtml('social.icons') ?>
            </div>
        </div>
    </div>

    <div class="py-3 mx-auto bg-[#070914] border-b border-t border-[#1F2937]">
        <?= $block->getChildHtml('payment_icons') ?>
        <div class="block lg:hidden">
            <?= $block->getChildHtml('copyright') ?>
        </div>
    </div>

    <div class="bg-[#070914] flex p-6">
        <div class="w-full mx-auto flex items-center justify-center lg:justify-between">
            <div class="hidden lg:block">
                <?= $block->getChildHtml('copyright') ?>
            </div>
            <a href="https://studioraz.co.il/"
               target="_blank"><?= $icons->renderHtml('studioraz-logo', 'text-white w-[113px] h-[31px]', 96, 50) ?></a>
        </div>
    </div>
</div>
