<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var SvgIcons $icons */

$icons = $viewModels->require(SvgIcons::class);
?>
<div class="text-base leading-6 relative border-t border-global-borders-subtle">
    <?= $block->getChildHtml('newsletter') ?>

    <?php $footerMenu = trim((string) $block->getChildHtml('menu-footer')); ?>
    <?php $storeColumn = trim((string) $block->getChildHtml('footer-column-store')); ?>
    <?php if ($footerMenu !== '' || $storeColumn !== ''): ?>
        <div class="bg-gray-100 lg:py-[32px]">
            <div class="container mx-auto px-7 pt-3 pb-2 lb:pt-0 lg:pb-0 lg:flex lg:justify-between">
                <?= $footerMenu ?>
                <?= /** @noEscape */ $storeColumn ?>

                <?php $socialIcons = trim((string) $block->getChildHtml('social.icons')); ?>
                <?php if ($socialIcons !== ''): ?>
                    <div class="lg:mb-[32px] lg:order-last">
                        <?= $socialIcons ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>

    <div class="flex items-center justify-center p-3 mx-auto max-lg:flex-col-reverse max-lg:gap-3 lg:grid lg:grid-cols-3 border-t border-global-borders-subtle">
        <div class="hidden lg:block lg:justify-self-start">
            <?= $block->getChildHtml('copyright') ?>
        </div>
        <div class="flex flex-col items-center gap-3 lg:justify-self-center">
            <?= $block->getChildHtml('payment_icons') ?>
            <a href="https://studioraz.co.il/"
               target="_blank"><?= $icons->renderHtml('studioraz-logo', 'text-black', 80) ?></a>
        </div>
        <div class="block lg:hidden">
            <?= $block->getChildHtml('copyright') ?>
        </div>
    </div>
</div>
