<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentCategory;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Catalog\Block\Product\ListProduct;
use Magento\Framework\Escaper;
use Magento\Wishlist\Helper\Data as WishlistHelper;
use Magento\Wishlist\Block\Customer\Wishlist\Items;

/** @var ListProduct $block */
/** @var Escaper $escaper */
/** @var Items $block */
/** @var ViewModelRegistry $viewModels */
/** @var ProductPage $productViewModel */
/** @var CurrentCategory $currentCategoryViewModel */
/** @var \Magento\Catalog\Model\Product $product */
/** @var LucideIcons $lucideIcons */
/** @var WishlistHelper $wishlistHelper */

$productViewModel = $viewModels->require(ProductPage::class);
$productListItemViewModel = $viewModels->require(ProductListItem::class);
$currentCategoryViewModel = $viewModels->require(CurrentCategory::class);
$lucideIcons = $viewModels->require(LucideIcons::class);
$wishlistHelper = $this->helper(WishlistHelper::class);
$columns = $block->getColumns();
?>

<?php if (!count($block->getItems())): ?>
    <div class="message info empty">
        <span><?= $escaper->escapeHtml(__('This Wish List has no Items')) ?></span>
    </div>
<?php else: ?>
    <div class="products products-grid wishlist">
        <ul role="list"
            class="mx-auto pt-0 grid gap-4 md:gap-5 grid-cols-1 min-[370px]:grid-cols-2 md:grid-cols-3 xl:grid-cols-4"
        >
            <?php foreach ($block->getItems() as $item): ?>
                <?php
                $product = $item->getProduct();
                $productUrl = $wishlistHelper->getProductUrl($item);
                $urlHash = explode('#', $productUrl, 2);
                $editProductUrl = $block->getUrl('wishlist/index/configure', ['id' => $item->getId()])
                    . (isset($urlHash[1]) ? '#' . $urlHash[1] : '');
                $product->setData('_render_context_data', [
                    'scope' => 'wishlist',
                    'item' => $item,
                ]);
                ?>
                <li class="flex flex-col h-auto">
                    <?= $productListItemViewModel->getItemHtml(
                        $product,
                        $block,
                        'grid',
                        \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW,
                        'category_page_grid',
                        false
                    ); ?>
                    <div class="flex gap-2">
                        <?php if ($product->isVisibleInSiteVisibility()): ?>
                            <a
                                class="btn p-2"
                                href="<?= $escaper->escapeUrl($editProductUrl) ?>"
                            >
                                <?= $lucideIcons->pencilHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                                <span class="sr-only">
                                    <?= $escaper->escapeHtml(__('Edit %1', $product->getName())) ?>
                                </span>
                            </a>
                        <?php endif; ?>
                        <button
                            type="button"
                            data-role="remove"
                            onclick='event.preventDefault(); hyva.postForm(<?= /* @noEscape */ $wishlistHelper->getRemoveParams($item) ?>)'
                            class="btn p-2"
                        >
                            <?= $lucideIcons->trashHtml('', 20, 20); ?>
                            <span class="sr-only">
                                <?= $escaper->escapeHtml(__('Remove item %1', $product->getName())) ?>
                            </span>
                        </button>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<?php foreach ($columns as $column): ?>
    <?= $column->getAdditionalHtml() ?>
<?php endforeach; ?>
