<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Magento\Wishlist\Block\Customer\Wishlist\Item\Column;
use Magento\Framework\Escaper;
use Magento\Catalog\Model\Product;
use Magento\Wishlist\Helper\Data;
use Magento\Wishlist\Model\Item;

/** @var Column $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var Product $product */
/** @var Item $item */
/** @var LucideIcons $lucideIcons */
/** @var Data $helper */

$helper = $this->helper(Data::class);
$lucideIcons = $viewModels->require(LucideIcons::class);
$product = $block->getProduct();
$renderContextData = $product->getData('_render_context_data');
$item = $renderContextData['item'];
?>

<button type="button"
        title="<?= $escaper->escapeHtmlAttr(__('Remove Item')) ?>"
        @click.prevent='hyva.postForm(<?= $helper->getRemoveParams($item) ?>)'
        class="rounded-full w-8 h-8 inline-flex shrink-0 items-center justify-center text-slate-500 bg-slate-200 hover:text-primary hover:bg-slate-100"
        data-role="remove"
>
    <?= $lucideIcons->renderHtml('trash-2', '', 16, 16, ['aria-hidden' => 'true']) ?>
</button>
