<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\LucideIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

$storeConfig = $viewModels->require(StoreConfig::class);
$maxItemsToDisplay = $storeConfig->getStoreConfig('checkout/sidebar/max_items_display_count');

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

$miniCartOptionShowSku = $block->getShowSku() !== null ? (bool) $block->getShowSku() : false;

$qtySpinnerBlock = $block->getChildBlock('qty_spinner');
$clearCartBlock = $block->getChildBlock('clear_cart');
?>

<script>
    function initCartDrawer() {
        return {
            open: false,
            isLoading: false,
            cart: {},
            maxItemsToDisplay: <?= (int) $maxItemsToDisplay ?>,
            itemsCount: 0,
            showSku: <?= $miniCartOptionShowSku ? 'true' : 'false' ?>,
            autocompleteNumber: 100,
            init() {
                if (document.prerendering) {
                    document.addEventListener("prerenderingchange", () => {
                        window.dispatchEvent(
                            new CustomEvent('reload-customer-section-data')
                        );
                    }, { once: true });
                }
            },
            showDetails() {
                return this.item.options && this.item.options.length || this.showSku;
            },
            cartIsEmpty() {
                return this.itemsCount === 0
            },
            getData() {
                const data = this.$event.detail.data;

                if (data.cart) {
                    this.cart = data.cart;
                    this.itemsCount = data.cart.items && data.cart.items.length || 0;
                    this.setCartItems();
                }
                this.isLoading = false;
            },
            cartItems: [],
            getItemCountTitle() {
                return hyva.strf('<?= $escaper->escapeJs(__('%0 of %1 products in cart displayed')) ?>', this.maxItemsToDisplay, this.itemsCount)
            },
            shouldShowItemCount() {
                return this.maxItemsToDisplay && this.maxItemsToDisplay < this.itemsCount;
            },
            setCartItems() {
                this.cartItems = this.cart.items && this.cart.items.sort((a, b) => b.item_id - a.item_id) || [];

                if (this.maxItemsToDisplay > 0) {
                    this.cartItems = this.cartItems.slice(0, parseInt(this.maxItemsToDisplay, 10));
                }
            },
            updateItemQty(event) {
                const form = event.target;
                this.isLoading = true;
                hyvaAjaxFormMinicart({ form, redirect: false }, () => {
                    this.isLoading = false;
                });
            },
            deleteItemFromCart() {
                const itemId = this.item.item_id;
                const formKey = hyva.getFormKey();
                this.isLoading = true;

                hyvaAjaxFormMinicart({
                    url: BASE_URL + 'checkout/sidebar/removeItem/',
                    body: 'form_key=' + formKey + '&item_id=' + itemId,
                    message: '<?= $escaper->escapeJs(__('You removed the item.')) ?>'
                }, () => {
                    this.isLoading = false
                });
            },
            toggleCartDrawer(event) {
                this.open = event.detail?.isOpen ?? !this.open;
            },
            openCartDrawer() {
                this.open = true;
            },
            closeCartDrawer() {
                this.open = false;
            },
            getSectionDataExtraActions() {
                if (!this.cart.extra_actions) {
                    return '';
                }

                const contentNode = document.createElement('div');
                contentNode.innerHTML = this.cart.extra_actions;

                hyva.activateScripts(contentNode);

                return contentNode.innerHTML;
            },
            productIsVisibleInSite() {
                return this.item.product_has_url && this.item.is_visible_in_site_visibility
            },
            productIsNotVisibleInSite() {
                return !this.productIsVisibleInSite()
            },
            productIsNotGroupedAndVisibleInSite() {
                return this.item.product_type !== 'grouped' && this.item.is_visible_in_site_visibility
            },
            productAriaLabel() {
                return hyva.strf(this.$el.dataset.ariaLabel, this.item.product_name)
            },
            proceedToCheckout() {
                this.closeCartDrawer()

                this.$dispatch(
                    'toggle-authentication',
                    {
                        url: '<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>'
                    }
                )
            },
            setItemMessage(itemId, message) {
                const items = this.cartItems;
                items.forEach((item) => {
                    if (item.item_id === itemId) {
                        item.message = message;
                    }
                });
            },
            cartListeners: {
                ['@private-content-loaded.window'](event) {
                    this.getData(event.detail.data);
                },
                ['@toggle-cart.window'](event) {
                    this.toggleCartDrawer(event);
                },
                ['@minicart-error-message.window'](event) {
                    if (!event.detail) return;
                    const { itemId, message } = event.detail;
                    this.setItemMessage(itemId, message);
                },
                ["@pageshow.window"](event) {
                    if (event.persisted) {
                        this.open = false;
                        window.dispatchEvent(new CustomEvent("reload-customer-section-data"));
                    }
                }
            }
        }
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('initCartDrawer', initCartDrawer);
    }, { once: true })

    async function hyvaAjaxFormMinicart(
        {
            form = null,
            url = '',
            body = '',
            redirect = 'default',
            message = '',
        } = {},
        callback = () => {}
    ) {
        const formData = body ? body : (form ? new FormData(form) : '');
        const postUrl = url ? url : (form ? form.action : '');
        if (!formData || !postUrl) {
            console.warn('You must provide the form or formData and postUrl!');
            return;
        }

        const formUenc = hyva.getUenc();
        const itemId = body ? new URLSearchParams(body).get('item_id') : formData.get('item_id');
        let bodyUrl = new URLSearchParams(formData);
        bodyUrl.append('uenc', formUenc);

        try {
            const response = await fetch(postUrl, {
                method: 'POST',
                body: bodyUrl.toString(),
                mode: 'cors',
                credentials: 'include',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
                    'X-Requested-With': 'XMLHttpRequest'
                }
            });

            if (!response.ok) {
                return form.submit();
            }

            if (redirect === 'default' && response.redirected) {
                return window.location.href = response.url;
            } else if (redirect !== 'default' && redirect !== false) {
                return window.location.href = redirect;
            }

            const responseBody = await response.json();

            if (!responseBody.success) {
                throw responseBody.error_message;
            }

            window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
        } catch (error) {
            window.dispatchEvent(new CustomEvent('minicart-error-message', { detail: { itemId, message: error } }));
        } finally {
            callback();
        }
    }

    function initCartItemLoader(itemId) {
        return {
            isLoading: false,
            isAfterLoading: false,
            eventListeners: {
                ['@update-qty-' + itemId + '-before.window'](event) {
                    this.isLoading = true;
                },
                ['@update-qty-' + itemId + '-after.window'](event) {
                    this.isAfterLoading = true;

                    setTimeout(() => {
                        this.isLoading = false;
                        this.isAfterLoading = false;
                    }, 500);
                },
            }
        }
    }
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<dialog
        id="cart-drawer"
        aria-labelledby="cart-drawer-title"
        class="w-[480px] md:w-[640px] h-full max-h-full me-0 open:flex flex-col transition ease-out duration-300 motion-reduce:duration-0 rounded-e-none"
        x-data="initCartDrawer"
        x-bind="cartListeners"
        x-show="open"
        x-htmldialog="closeCartDrawer"
        closeby="any"
        x-transition:enter="transition ease-in-out duration-500"
        x-transition:enter-start="translate-x-full rtl:-translate-x-full"
        x-transition:enter-end="translate-x-0"
        x-transition:leave="transition ease-in-out duration-300"
        x-transition:leave-start="translate-x-0"
        x-transition:leave-end="translate-x-full rtl:-translate-x-full"
>
    <?= $block->getChildHtml('cart-drawer.top'); ?>

    <div class="flex gap-2 justify-between items-center">
        <div class="flex">
            <p id="cart-drawer-title" class="flex items-center">
                <strong class="text-base lg:text-lg text-salte-900"><?= $escaper->escapeHtml(__('My Cart')) ?></strong>
                <template x-if="itemsCount">
                    <span class="ms-[6px]">
                        (<span class="leading-5 text-slate-950"
                               x-html="cart.summary_count"></span> <span><?= $escaper->escapeHtml(__('Items')) ?></span>)
                    </span>
                </template>
                <?= $clearCartBlock ? $clearCartBlock->toHtml() : '' ?>
            </p>
        </div>
        <button
                type="button"
                class="btn bg-transparent border-transparent p-2"
                @click="closeCartDrawer"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Close minicart')) ?>"
        >
            <?= $lucideIcons->xHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
        </button>
    </div>

    <?= $block->getChildHtml('cart-drawer.items.before'); ?>

    <template x-if="cartIsEmpty">
        <div class="grow grid place-items-center">
            <div class="text-center">
                <?= $lucideIcons->shoppingBasketHtml('inline-block text-fg/30 max-w-full h-auto', 120, 120, ['aria-hidden' => 'true']); ?>
                <p class="mt-10 text-xl">
                    <strong><?= $escaper->escapeHtml(__('Cart is empty')) ?></strong>
                </p>
            </div>
        </div>
    </template>

    <div class="overflow-y-auto grow max-h-[calc(100dvh-258px)] lg:max-h-[calc(100vh-260px)]">
        <?= $block->getChildHtml('cart-drawer.items.scrollable.before'); ?>

        <template x-if="itemsCount">
            <ul class="grow flex flex-col overflow-y-auto overscroll-y-contain mask-overflow mask-dir-y">
                <template x-for="item in cartItems" :key="item.item_id">
                    <li class="minicart-product-item box-border py-2 lg:py-3 [&:not(:last-child)]:border-b border-slate-200">
                        <div class="relative flex items-start justify-between gap-3 transition duration-150 ease-in-out">
                            <div class="w-24 flex flex-col items-center">
                                <template x-if="productIsVisibleInSite">
                                    <a :href="item.product_url"
                                       :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Product "%0"')) ?>', item.product_name)"
                                       :title="item.product_name"
                                    >
                                        <img
                                                :src="item.product_image.src"
                                                :width="item.product_image.width"
                                                :height="item.product_image.height"
                                                loading="lazy"
                                                :alt="item.product_name"
                                        >
                                    </a>
                                </template>
                                <template x-if="productIsNotVisibleInSite">
                                    <div>
                                        <img
                                                :src="item.product_image.src"
                                                :width="item.product_image.width"
                                                :height="item.product_image.height"
                                                loading="lazy"
                                                :alt="item.product_name"
                                        />
                                    </div>
                                </template>
                            </div>
                            <div class="w-[calc(100%_-_108px)]">
                                <div class="flex items-start justify-between gap-[8px] mb-5">
                                    <div class="">
                                        <template x-if="productIsVisibleInSite">
                                            <a :href="item.product_url" class="transition duration-150 ease-in-out no-underline">
                                                <p class="text-sm font-bold leading-5 text-[#334155]">
                                                    <span x-html="item.product_name"></span>
                                                </p>
                                            </a>
                                        </template>
                                        <template x-if="productIsNotVisibleInSite">
                                            <div class="transition duration-150 ease-in-out no-underline">
                                                <p class="text-sm font-bold leading-5 text-[#334155]">
                                                    <span x-html="item.product_name"></span>
                                                </p>
                                            </div>
                                        </template>
                                        <template x-if="showDetails">
                                            <dl class="table text-sm">
                                                <template x-if="showSku">
                                                    <div class="table-row">
                                                        <dt class="table-cell font-normal min-w-16 pe-2 pb-2">
                                                            <?= $escaper->escapeHtml(__('Sku')) ?>
                                                        </dt>
                                                        <dd class="table-cell font-bold pb-2" x-html="item.product_sku"></dd>
                                                    </div>
                                                </template>
                                                <template x-for="option in item.options">
                                                    <div class="table-row">
                                                        <dt
                                                                class="table-cell font-normal min-w-16 pe-2 pb-2"
                                                                x-text="option.label"
                                                        ></dt>
                                                        <dd class="table-cell font-bold pb-2" x-html="option.value"></dd>
                                                    </div>
                                                </template>
                                            </dl>
                                        </template>
                                    </div>
                                    <button
                                            type="button"
                                            class="btn bg-transparent border-transparent p-2"
                                            @click="deleteItemFromCart"
                                            data-aria-label="<?= $escaper->escapeHtmlAttr(__('Remove product "%0" from cart')) ?>"
                                            :aria-label="productAriaLabel"
                                    >
                                        <?= $lucideIcons->trashHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                                    </button>
                                </div>
                                <div class="flex w-full items-center justify-between">
                                    <div class="flex flex-col lg:flex-row lg:flex-row-reverse lg:items-center lg:gap-2">
                                        <template x-if="item.product_regular_price > item.product_price_value">
                                                    <span class="line-through text-[#94A3B8] text-sm"
                                                          x-html="hyva.formatPrice(item.product_regular_price_total)"></span>
                                        </template>
                                        <span class="text-base font-bold leading-7"
                                              x-html="item.product_price_total"
                                              :class="{
                                                  'special-price': item.product_regular_price > item.product_price_value
                                              }"></span>
                                    </div>
                                    <?= $qtySpinnerBlock ? $qtySpinnerBlock->toHtml() : '' ?>
                                </div>
                            </div>
                            <div x-data="initCartItemLoader(item.item_id)"
                                 class="!-m-1.5"
                                 x-cloak
                                 x-show="isLoading"
                                 x-bind="eventListeners"
                            >
                                <div class="absolute bg-opacity-60 z-10 inset-0 flex items-center justify-center"
                                     x-transition:leave="ease-in-out duration-200"
                                     x-transition:leave-start="opacity-100"
                                     x-transition:leave-end="opacity-0">
                                    <div class="flex items-center">
                                        <div class="minicart-item-icon-loading absolute"
                                             x-show="!isAfterLoading"
                                             x-transition:leave="transform transition ease-in-out duration-300"
                                             x-transition:leave-start="opacity-100 scale-100"
                                             x-transition:leave-end="opacity-0 scale-0">
                                            <svg class="animate-spin h-5 w-5 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none"
                                                 viewBox="0 0 24 24">
                                                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                                                <path class="opacity-75" fill="currentColor"
                                                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z">
                                                </path>
                                            </svg>
                                        </div>
                                        <div class="minicart-item-icon-check absolute text-green-600"
                                             x-show="isAfterLoading"
                                             x-transition:enter="transform transition ease-in-out duration-300"
                                             x-transition:enter-start="opacity-0 scale-0"
                                             x-transition:enter-end="opacity-100 scale-100">
                                            <?= $lucideIcons->checkHtml('', 24, 24); ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <template x-if="item.message">
                            <div class="cart item message error mt-4 mb-0 max-sm:w-[97%] mx-auto">
                                <div x-html="item.message"></div>
                            </div>
                        </template>
                    </li>
                </template>
            </ul>
        </template>

        <?= $block->getChildHtml('cart-drawer.items.scrollable.after'); ?>
    </div>


    <?= $block->getChildHtml('cart-drawer.items.after'); ?>

    <?= $block->getChildHtml('cart-drawer.bottom'); ?>

    <template x-if="itemsCount">
        <div class="-mx-4 lg:-mx-6 px-4 lg:px-6 pt-2 -mb-2 shadow-[0_-2px_4px_0_rgba(0,0,0,0.06)]">
            <?= $block->getChildHtml('cart-drawer.totals.before'); ?>

            <dl class="flex gap-2 justify-between items-center text-sm font-bold">
                <dt class="text-slate-900"><?= $escaper->escapeHtml(__('Subtotal')) ?></dt>
                <dd class="text-price" x-html="cart.subtotal"></dd>
            </dl>
            <template x-if="cart.discountAmount != 0">
                <dl class="flex gap-2 justify-between items-center text-sm font-bold">
                    <dt class="text-slate-900"><?= $escaper->escapeHtml(__('Discount')) ?></dt>
                    <dd class="text-price" x-html="cart.discount"></dd>
                </dl>
            </template>
            <template x-if="cart.shippingAmount != 0">
                <dl class="flex gap-2 justify-between items-center text-sm font-bold">
                    <dt class="text-slate-900"><?= $escaper->escapeHtml(__('Shipping')) ?></dt>
                    <dd class="text-price" x-html="cart.shipping"></dd>
                </dl>
            </template>
            <dl class="flex gap-2 justify-between items-center text-base lg:text-lg font-bold">
                <dt class="text-slate-900"><?= $escaper->escapeHtml(__('Grand Total')) ?></dt>
                <dd class="text-price" x-html="cart.grandTotal"></dd>
            </dl>

            <div class="flex flex-col gap-y-4 mt-2">
                <a
                        @click.prevent.stop="proceedToCheckout"
                        href="<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>"
                        class="btn btn-primary"
                >
                    <?= $escaper->escapeHtml(__('Continue to Checkout')) ?>
                </a>
                <div class="text-center text-sm font-semibold text-[#334155]">
                    <?= $escaper->escapeHtml(__('Discounts and promotions will be calculated at checkout.')) ?>
                </div>
                <div x-html="getSectionDataExtraActions"></div>
                <?= $block->getChildHtml('extra_actions'); ?>
            </div>
        </div>
    </template>

    <template x-if="cartIsEmpty">
        <div class="flex flex-col">
            <button
                    type="button"
                    @click="closeCartDrawer"
                    class="btn btn-primary"
            ><?= $escaper->escapeHtml(__('Continue Shopping')) ?></button>
        </div>
    </template>

    <?= $block->getChildHtml('loading') ?>
</dialog>
