<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Customer\Block\Widget\Company;
use Magento\Customer\Helper\Address as AddressHelper;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Company $block */

$validationClass = $this->helper(AddressHelper::class)->getAttributeValidationClass('company');

?>
<div class="field field-reserved floating-labels company <?= $block->isRequired() ? 'required' : '' ?>">
    <div class="control">
        <input type="text"
               name="company"
               id="company"
               <?php if ($block->isRequired()): ?>
                   required
               <?php endif; ?>
               value="<?= $escaper->escapeHtmlAttr($block->getCompany()) ?>"
               title="<?= $escaper->escapeHtmlAttr(__('Company')) ?>"
               placeholder=" "
               class="form-input w-full peer <?= $escaper->escapeHtmlAttr($validationClass) ?>"
        >
        <label for="company" class="label floating-labels-label">
            <?= $escaper->escapeHtml(__('Company')) ?>
        </label>
    </div>
</div>
