<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Customer\Block\Widget\Fax;
use Magento\Customer\Helper\Address as AddressHelper;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Fax $block */

$validationClass = $escaper->escapeHtmlAttr($this->helper(AddressHelper::class)->getAttributeValidationClass('fax'));

?>
<div class="field field-reserved floating-labels fax <?= $block->isRequired() ? 'required' : '' ?>">
    <div class="control">
        <input type="text"
               name="fax"
               id="fax"
               value="<?= $escaper->escapeHtmlAttr($block->getFax()) ?>"
               title="<?= $escaper->escapeHtmlAttr(__('Fax')) ?>"
               placeholder=" "
               class="form-input peer w-full <?= $validationClass ?: '' ?>"
               <?= $block->isRequired() ? ' required' : '' ?>
        >
        <label for="fax" class="label floating-labels-label">
            <span><?= $escaper->escapeHtml(__('Fax')) ?></span>
        </label>
    </div>
</div>
