<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Customer\Block\Widget\Gender;
use Magento\Customer\Helper\Address as AddressHelper;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Gender $block */

?>
<div class="field field-reserved floating-labels gender<?= $block->isRequired() ? ' required' : ''?>">
    <div class="control">
        <select id="<?= $escaper->escapeHtmlAttr($block->getFieldId('gender')) ?>"
                name="<?= $escaper->escapeHtmlAttr($block->getFieldName('gender')) ?>"
                title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('gender')) ?>"
                class="form-select peer w-full"
            <?php if ($block->isRequired()): ?>required<?php endif; ?>>
            <?php $options = $block->getGenderOptions(); ?>
            <?php $value = $block->getGender(); ?>
            <?php foreach ($options as $option): ?>
                <option value="<?= $escaper->escapeHtmlAttr($option->getValue()) ?>"
                    <?= ($option->getValue() == $value) ? 'selected="selected"' : '' ?>
                ><?= $escaper->escapeHtml(__($option->getLabel())) ?></option>
            <?php endforeach;?>
        </select>
        <label class="label floating-labels-label" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('gender')) ?>">
            <span><?= $escaper->escapeHtml($block->getStoreLabel('gender')) ?></span>
        </label>
    </div>
</div>
