<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Customer\Block\Widget\Taxvat;
use Magento\Customer\Helper\Address as AddressHelper;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Taxvat $block */
?>
<div class="field field-reserved floating-labels taxvat <?= $block->isRequired() ? 'required' : ''; ?>">
    <div class="control">
        <input type="text"
               id="<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')) ?>"
               name="<?= $escaper->escapeHtmlAttr($block->getFieldName('taxvat')) ?>"
               value="<?= $escaper->escapeHtmlAttr($block->getTaxvat()) ?>"
               title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('taxvat')) ?>"
               placeholder=" "
               class="form-input peer <?= $escaper->escapeHtmlAttr($this->helper(AddressHelper::class)->getAttributeValidationClass('taxvat')) ?>"
            <?= $block->isRequired() ? ' required' : '' ?>
        >
        <label class="label floating-labels-label" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')) ?>">
           <?= $escaper->escapeHtml($block->getStoreLabel('taxvat')) ?>
        </label>
    </div>
</div>
