<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Customer\Block\Widget\Telephone;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Telephone $block */
?>

<div class="field field-reserved floating-labels telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <div class="control">
        <input type="tel"
               name="telephone"
               id="telephone"
               <?php if ($block->isRequired()): ?>required<?php endif; ?>
               @input.debounce="onChange"
               data-validate='{"telephone": true}'
               value="<?= $escaper->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
               placeholder=" "
               class="form-input peer <?= $escaper->escapeHtmlAttr(
                   $block->getAttributeValidationClass('telephone')
               ) ?>"
        >
        <label for="telephone" class="label floating-labels-label">
            <?= $escaper->escapeHtml(__('Phone Number')) ?>
        </label>
    </div>
</div>
