<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Newsletter\Block\Subscribe;
use Hyva\Theme\ViewModel\ReCaptcha;
use Hyva\Theme\Model\ViewModelRegistry;

/**
 * @var Template $block
 * @var Escaper $escaper
 * @var Subscribe $newsletterBlock
 * @var ViewModelRegistry $viewModels
 */

$newsletterBlock = $block->getLayout()->createBlock(Subscribe::class);
$recaptcha = $block->getData('viewModelRecaptcha');
?>

<div class="container mx-auto px-7 lg:mt-8">
    <div class="text-center mb-[18px] lg:mb-[21px]">
        <div class="uppercase font-bold mb-[10px] lg:mb-2 text-gray-700 pt-[38px] lg:pt-14 text-[22px] lg:text-[32px]">
            <?= $escaper->escapeHtml(__('Be the first to know')) ?>
        </div>
        <div class="text-[rgb(111,113,118)] text-base">
            <?= $escaper->escapeHtml(__('Subscribe for the latest news and our best offers.')) ?>
        </div>
    </div>

    <div class="lg:mt-[23px] mb-[6px] lg:mb-9 md:max-w-2xl md:mx-auto">
        <form class="flex flex-wrap relative form-newsletter-validate"
              action="<?= $escaper->escapeUrl($newsletterBlock->getFormActionUrl()) ?>"
              method="post"
              x-data="{...initNewsletterForm(), ...hyva.formValidation($el), ...initNewsletterFormWrapper()}"
              @submit.prevent="submitForm()"
              x-ref="form"
              id="newsletter-validate-detail"
        >
            <?= $block->getBlockHtml('formkey') ?>

            <?= $block->getBlockHtml(ReCaptcha::RECAPTCHA_INPUT_FIELD_BLOCK) ?>

            <div class="w-full md:w-2/3 mb-2 md:pe-2 relative" id="newsletter-subscribe-wrapper">
                <ul x-show="errorMessages.length" class="form-error-messages w-full absolute bottom-full">
                    <template x-for="errorMessage in errorMessages">
                        <li x-html="errorMessage" class='text-center px-4 text-pastel-red'></li>
                    </template>
                </ul>
                <div class="field field-reserved floating-labels">
                    <div class="control">
                        <input type="email"
                               name="email"
                               id="newsletter-subscribe"
                               data-validate='{"required": true}'
                               @change="onChange"
                               x-ref="input"
                               placeholder=" "
                               class="peer h-12 border-gray-300 bg-white w-full p-3 border rounded-md shadow-sm placeholder:text-gray-400 outline-none focus:ring-form-focus focus:ring-1 hover:border-form-hover"
                               :disabled="isLoading"
                               :class="{'invalid-input': errorMessages.length}"
                        />
                        <label class="floating-labels-label"
                               for="newsletter-subscribe"
                               aria-label="<?= $escaper->escapeHtmlAttr(__('Email address')) ?>"
                        >
                            <?= $escaper->escapeHtml(__('Email address')) ?>
                        </label>
                    </div>
                </div>
                <?= $newsletterBlock->getBlockHtml('formkey') ?>
            </div>

            <div class="w-full md:w-1/3">
                <button type="button"
                        @click="formWrapperSubmit($event)"
                        id="newsletter-submit"
                        class="btn btn-primary h-12 p-3 cursor-pointer w-full rounded-md shadow-sm font-bold"
                        :disabled="isLoading">
                    <span x-show="!isLoading"><?= $escaper->escapeHtmlAttr(__('Subscribe')) ?></span>
                    <span x-show="isLoading"
                          class="block mx-auto w-2 h-2 bg-white rounded-full animate-shadow-expand-x"></span>
                </button>
                <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
            </div>

            <div class="w-full my-2 md:ps-[2px]">
                <label for="newsletter-checkbox"
                       class="newsletter-label flex gap-2 lg:items-center text-[13px] lg:text-2sm text-[rgb(111,113,118)]">
                    <input type="checkbox" name="newsletter-checkbox" id="newsletter-checkbox" checked required
                           :disabled="isLoading"/>
                    <span><?= $escaper->escapeHtml(__('I give my consent to receive marketing emails and SMSs')) ?></span>
                </label>
            </div>
        </form>
    </div>

    <div class="w-full">
        <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
    </div>
</div>

<script>
    function initNewsletterForm() {
        return {
            errors: 0,
            hasCaptchaToken: 0,
            displayErrorMessage: false,
            errorMessages: [],
            isLoading: false,
            submitForm() {
                const $form = document.querySelector('#newsletter-validate-detail');

                <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>

                if (this.errors !== 0) {
                    return;
                }

                const formData = new FormData($form);
                const postUrl = `${BASE_URL}sr_newsletter/subscriber/newajax`;

                this.isLoading = true;

                fetch(postUrl, {
                    method: 'POST',
                    headers: {
                        contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                        'Accept': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest',
                    },
                    body: formData,
                })
                    .then(response => {
                        if (response.redirected) {
                            window.location.href = response.url;
                        } else if (response.ok) {
                            return response.json();
                        } else {
                            this.dispatchMessage('warning', '<?= __('Subscribe to Newsletter request failed') ?>');
                            console.error('Subscribe to Newsletter request failed. Response - ', response);
                        }
                    })
                    .then(response => {
                        if (response.success) {
                            $form.reset();
                        }

                        const reloadCustomerDataEvent = new CustomEvent('reload-customer-section-data');
                        window.dispatchEvent(reloadCustomerDataEvent);

                        this.isLoading = false;
                    })
                    .catch(error => {
                        console.error('Fetch error: ', error);
                    });
            },
            dispatchMessage(type, text, hideAfter = 5000) {
                typeof window.dispatchMessages && window.dispatchMessages([{type, text}, hideAfter]);
            },

            //custom validation functions
            /*init() {
                this.$refs.form.addEventListener( "invalid", function( event ) {
                    event.preventDefault();
                    this.validate();
                }.bind(this), true );
            },*/
            /*validate() {
                this.errorMessages = [];
                let invalidFields = this.$refs.form.querySelectorAll( ":invalid" );

                invalidFields.forEach(function (field) {
                    this.errorMessages.push(field.validationMessage);
                }.bind(this))

                if ( invalidFields.length > 0 ) {
                    invalidFields[ 0 ].focus();
                }

                return this.errorMessages.length === 0;
            }*/
        }
    }

    function initNewsletterFormWrapper() {
        return {
            formWrapperSubmit(event) {
                event.preventDefault();

                this.validate()
                    .then(() => {
                        // all fields validated
                        this.submitForm();
                    })
                    .catch((invalid) => {
                        if (invalid.length > 0) {
                            invalid[0].focus();
                        }
                    });
            }
        }
    }
</script>
