<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\PaymentIcons\ViewModel\PaymentIconsLight;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var PaymentIconsLight $paymentIcons */

$paymentIcons = $viewModels->require(PaymentIconsLight::class);
?>

<div class="text-center flex md:gap-2 flex-wrap justify-center mb-0">
    <?= $paymentIcons->googlePayHtml('max-md:mx-1 max-md:mb-2', 40) ?>
    <?= $paymentIcons->applePayHtml('max-md:mx-1 max-md:mb-2', 40) ?>
    <?= $paymentIcons->mastercardHtml('max-md:mx-1 max-md:mb-2', 40) ?>
    <?= $paymentIcons->visaHtml('max-md:mx-1 max-md:mb-2', 40) ?>
    <?= $paymentIcons->americanExpressHtml('max-md:mx-1 max-md:mb-2', 40) ?>
</div>
