<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var Template $block */
/** @var SearchHelper $helper */
/** @var \Mirasvit\SearchAutocomplete\Block\Injection $block */
/** @var LucideIcons $lucideIcons */
/** @var ViewModelRegistry $viewModels */
/** @var SvgIcons $icons */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Search\Helper\Data as SearchHelper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\SvgIcons;

$config = $block->getJsConfig();
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

$helper         = $this->helper(SearchHelper::class);
$col2           = $config['layout'] == "2columns";
$titleCSS       = 'text-base font-bold leading-6';
$titleNumberCSS = 'text-gray-500 ms-1';

$itemCSS     = 'flex';
$itemNameCSS = 'text-sm font-normal leading-5 cursor-pointer';

$lucideIcons = $viewModels->require(LucideIcons::class);
$icons = $viewModels->require(SvgIcons::class);
?>

<?php /** Main Search Area */ ?>

<div
    class="relative"
    x-data="initMirasvitSearch()"
    @click.away="closeSearch; $nextTick(() => isSearchOpened())"
    x-init="calculatePositions()"
    @resize.window.debounce="calculatePositions()"
>
    <form class="relative w-full"
          id="search_mini_form"
          x-ref="searchForm"
          action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>"
          method="get"
          autocomplete="off">

        <label class="hidden" for="search" data-role="minisearch-label">
            <span><?= $escaper->escapeHtml(__('Search')) ?></span>
        </label>
        <div class="relative w-full flex">
            <input id="search"
                   x-ref="searchInput"
                   type="search"
                   name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                   value="<?= $escaper->escapeHtmlAttr($helper->getEscapedQueryText()) ?>"
                   placeholder="<?= $escaper->escapeHtmlAttr(__('Search entire store here...')) ?>"
                   maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                   class="w-full border-slate-300 rounded-l-md !rounded-e-none focus:border-primary focus:outline-none focus:ring-0"
                   x-on:keyup.debounce.300="doSearch(searchInput)"
                   x-on:focus.debounce.150="openSearch"
                   x-on:click.debounce.150="openSearch"
                   x-on:keydown.debounce.100="startSearch(searchInput)"
                   @keyup.enter="searchInput && $refs.searchForm.submit()"
                   x-model.fill="searchInput"
            />
            <button
                    type="submit"
                    class="action search btn btn-primary rounded-s-none rounded-e-md px-2"
                    title="<?= $escaper->escapeHtmlAttr(__('Search')) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Search')) ?>"
            >
                <?= $lucideIcons->searchHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
            </button>
            <button class="absolute end-[55px] top-0 h-full p-2"
                    x-show="canShowClearSearch()"
                    @click="clearSearch();"
                    title="<?= __('Clear search') ?>"
                    aria-label="<?= __('Clear search') ?>"
                    x-cloak
                    type="button"><?= $lucideIcons->xHtml('x-circle', 15, 15, ['title' => __('Clear search')]) ?></button>
        </div>
    </form>

    <div
        x-show="isOpen"
        @click="closeSearch; $nextTick(() => isSearchOpened())"
        class="fixed z-40 inset-0 top-[172px] md:top-[106px] bg-[rgba(0,0,0,0.24)]"
        :style="backdropStyles()"
        x-cloak></div>

    <div x-cloak x-show="isOpen" id="mirasvitSearchResults" :style="panelStyles()" class="mirasvit-search-results absolute top-full start-0 end-0 mt-5 bg-white z-[60] rounded-xl shadow-[-4px_4px_4px_0px_rgba(10,26,79,0.04)]">

        <div x-show="isLoading" class="min-h-[70px] md:min-h-[100px]">
            <?= $block->getChildHtml('loading.search.autocomplete') ?>
        </div>

        <?php if ($config['popularSearches']) : ?>
            <template x-if="hotSearch">
                <div class="p-4 md:p-6 flex flex-col" x-show="isOpen">
                    <p class="<?= $titleCSS ?>">
                        <?= $escaper->escapeHtml(__($config['popularTitle'])) ?>
                    </p>
                    <div class="mt-3 flex flex-wrap gap-[8px]">
                        <?php foreach ($config['popularSearches'] as $search) : ?>
                            <span x-on:click="hotSearchClickEvent"
                                  class="text-center text-sm font-medium leading-5 py-[6px] px-[10px] border border-slate-400 rounded-[26px] cursor-pointer hover:text-primary hover:border-primary active:text-primary active:border-primary">
                                    <?= $escaper->escapeHtml(__($search)) ?>
                                </span>
                        <?php endforeach; ?>
                    </div>
                </div>
            </template>
        <?php endif; ?>

        <template x-if="searchResults">
            <div x-show="!isLoading"
                class="overflow-y-hidden w-full rounded-xl p-[16px] pe-0 lg:p-[32px]"
                :class="{'search-scroll-panel': (searchProducts.length || searchCategories.length)}"
            >
                <div class="search-panel-content mx-auto justify-items-stretch lg:px-2 <?= $col2 ? 'flex flex-col lg:grid lg:gap-x-0 lg:grid-cols-12' : '' ?> rounded-xl">
                    <?php if ($col2) : ?>
                    <div class="col-span-12 lg:col-span-7 lg:order-first max-w-full">
                        <?php endif; ?>
                        <p class="order-1 text-base md:text-lg text-slate-900 font-bold leading-6 mb-3">
                            <?= __('Products') ?>
                        </p>
                        <div
                            class="scrollable-list order-2 mx-auto flex flex-col mb-[14px] pe-[18px] lg:pe-[32px] lg:mb-[20px] overflow-x-hidden overflow-y-auto"
                            :class="{'h-[calc(100dvh-469px)] lg:min-h-[386px] lg:h-[calc(100vh-690px)]': searchProducts.length}"
                        >
                            <template x-for="item in searchProducts">
                                <div class="flex bg-white flex-row w-full">
                                    <a x-bind:href="`${item.url}`" class="flex items-center justify-between gap-[8px] py-[6px] px-[8px] w-full rounded-lg hover:bg-gray-50 no-underline">
                                        <?php if ($config['isShowImage']): ?>
                                            <div class="flex items-center w-[80px]">
                                                <img x-bind:src="`${item.imageUrl}`" class="mx-auto w-[64px] h-auto"/>
                                            </div>
                                        <?php endif ?>
                                        <div class="w-full text-sm md:text-base">
                                            <h4 class="font-bold leading-6 text-black text-wrap" x-html="item.name"></h4>
                                            <?php if ($config['isShowDescription']): ?>
                                                <p class="truncate w-[135px]" x-html="item.description"></p>
                                            <?php endif ?>
                                            <?php if ($config['isShowPrice']): ?>
                                                <div class="flex items-center justify-start flex-row">
                                                    <span class="text-special-price font-medium leading-4" x-html="item.price"></span>
                                                </div>
                                            <?php endif ?>
                                        </div>
                                    </a>
                                </div>
                            </template>
                            <template x-if="searchProducts == ''">
                                <p class="text-xs lg:text-sm font-normal leading-4 lg:leading-5 text-slate-950"><?= $escaper->escapeHtml(__('No results found.')) ?></p>
                            </template>
                        </div>
                        <?php if ($col2) : ?>
                        <div class="w-full order-2 col-span-12 hidden lg:pe-[32px] lg:block">
                            <div class="flex items-center justify-end">
                                <a x-bind:href="numberResultsUrl" class="inline-flex items-center justify-between gap-[6px] no-underline text-primary hover:underline">
                                    <span class="text-sm leading-6 font-medium transition appearance-none" x-html="getNumberResults(numberResults)"></span>
                                    <?= $lucideIcons->renderHtml('arrow-right', '', 18, 18, []) ?>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div
                        class="order-4 pe-[18px] col-span-12 lg:col-span-5 lg:order-1 lg:border-s lg:border-s-slate-300 lg:ps-[32px]"
                        :class="{'lg:min-h-[476px] lg:h-[calc(100vh-600px)]': searchCategories.length}"
                    >
                        <?php endif; ?>

                        <template x-if="searchCategories != ''">
                            <div class="mb-2 lg:mb-[21px] pt-[18px] lg:pt-0 lg:pb-0 border-t border-t-slate-300 lg:border-none">
                                <p class="order-1 text-base md:text-lg text-slate-900 font-bold leading-6 mb-3"">
                                    <?= __('Categories') ?>
                                </p>
                                <div class="text-sm">
                                    <template x-for="(category, index) in searchCategories">
                                        <a x-bind:href="`${category.url}`" class="no-underline hover:underline !hover:text-primary">
                                            <div class="<?= $itemCSS ?>" :class="{ 'mb-[10px]': index !== searchCategories.length - 1 }">
                                                <span class="<?= $itemNameCSS ?>" x-html="getCategoryName(category.name)"></span>
                                            </div>
                                        </a>
                                    </template>
                                </div>
                            </div>
                        </template>

                        <template x-if="searchPages != ''">
                            <div class="mb-2 lg:mb-[21px] pb-3 lg:pb-0 border-b border-[#dddcdc] lg:border-none">
                                <p class="<?= $titleCSS ?> ps-7 mb-3 lg:mb-[10px]">
                                    <?= __('Pages') ?>
                                </p>
                                <div class="ps-7 lg:ps-2 px-2 text-[#121212] lg:border-t lg:border-[#dddcdc]">
                                    <template x-for="page in searchPages">
                                        <a x-bind:href="`${page.url}`" class="no-underline">
                                            <div class="<?= $itemCSS ?>">
                                                <span class="<?= $itemNameCSS ?>" x-html="page.name"></span>
                                            </div>
                                        </a>
                                    </template>
                                </div>
                            </div>
                        </template>

                        <template x-if="searchPosts != ''">
                            <div class="mb-2 lg:mb-[21px] pb-3 lg:pb-0 border-b border-[#dddcdc] lg:border-none">
                                <p class="<?= $titleCSS ?> ps-7 mb-3 lg:mb-[10px]">
                                    <?= __('Posts') ?>
                                    <small class="<?= $titleNumberCSS ?>">(<span x-html="searchPostsTotal"></span>)</small>
                                </p>
                                <div class="px-2 text-[#121212]">
                                    <template x-for="item in searchPosts">
                                        <a x-bind:href="`${item.url}`" class="no-underline">
                                            <div class="<?= $itemCSS ?>">
                                                <span class="<?= $itemNameCSS ?>" x-html="item.name"></span>
                                            </div>
                                        </a>
                                    </template>
                                </div>
                            </div>
                        </template>
                        <?php if ($col2) : ?>
                    </div>
                <?php endif; ?>

                    <div class="order-3 pe-[18px] lg:mt-0 w-full col-span-12 lg:hidden">
                        <div class="flex items-center justify-end mb-[16px]">
                            <a x-bind:href="numberResultsUrl" class="inline-flex items-center justify-between gap-[6px] no-underline text-primary">
                                <span class="text-base leading-6 font-medium appearance-none" x-html="getNumberResults(numberResults)"></span>
                                <?= $lucideIcons->renderHtml('arrow-right', '', 18, 18) ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </template>

        <template x-if="noResults">
            <div class="p-4 md:p-6 rounded-xl text-slate-900" x-show="!isLoading">
                <p class="text-sm font-normal leading-5" x-html="noResultsText"></p>

                <div class="flex flex-col mt-3">
                    <p class="<?= $titleCSS ?>">
                        <?= __('Hot Searches') ?>
                    </p>
                    <div class="mt-3 flex flex-wrap gap-[8px]">
                        <?php if ($config['popularSearches']) : ?>
                            <?php foreach ($config['popularSearches'] as $search) : ?>
                                <span x-on:click="hotSearchClickEvent"
                                      class="text-center text-sm font-medium leading-5 py-[6px] px-[10px] border border-slate-400 rounded-[26px] cursor-pointer hover:text-primary hover:border-primary active:text-primary active:border-primary">
                                    <?= $escaper->escapeHtml(__($search)) ?>
                                </span>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </template>
    </div>
</div>
<script>
    function initMirasvitSearch() {
        return {
            //initialize Variables
            hotSearch:             false,
            searchResults:         false,
            noResults:             false,
            isLoading:             false,
            isOpen:                false,
            blockConfig:           <?= json_encode($config); ?>,
            xhttp:                 false,
            noResultsText:         '',
            numberResults:         '',
            numberResultsUrl:      '',
            searchProductsTotal:   '',
            searchCategoriesTotal: '',
            searchPagesTotal:      '',

            searchProducts:   [],
            searchCategories: [],
            searchPages:      [],
            searchPosts:      [],

            searchMap: {
                'magento_cms_page':         'Pages',
                'magento_catalog_category': 'Categories',
                'magento_catalog_product':  'Products',
                'magefan_blog_post':        'Posts'
            },

            searchInput: '',

            categoryBreadcrumbsSeparator: `<?= $lucideIcons->renderHtml('chevron-right', 'inline ms-[2px] mb-[1px] [&>*:nth-child(1)]:stroke-[3]', 12, 10); ?>`,

            backdropTop: 0,
            panelMarginTop: 0,

            isSearchOpened() {
                this.$dispatch(this.isOpen ? 'lock-scrollbar' : 'release-scrollbar', {
                    name: 'search'
                });
            },

            hotSearchClickEvent: function (ev) {
                var hotSearchClick = event.currentTarget.innerText;
                this.searchInput = hotSearchClick;

                this.doSearch(hotSearchClick);
            },

            openSearch: function () {
                this.isOpen = true;
                this.isSearchOpened();

                if (this.searchInput >= this.blockConfig.minSearchLength) {
                    this.hideHotSearch();
                } else {
                    this.showHotSearch();
                    this.hideSearchResults();
                }
            },

            startSearch: function (e) {
                if (e) {
                    this.isOpen = true;
                }
            },

            closeSearch: function () {
                this.isOpen = false;
                this.searchInput = '';
            },

            showHotSearch: function () {
                this.noResults = false;
                this.hotSearch = true;
            },

            hideHotSearch: function () {
                this.hotSearch = false;
            },

            showSearchResults: function () {
                this.searchResults = true;
            },

            hideSearchResults: function () {
                this.searchResults = false;
            },

            showNoResults: function () {
                this.noResults = true;
            },

            hideNoResults: function () {
                this.noResults = false;
            },

            setNoResultsText(text) {
                if (!text) {
                    return;
                }

                this.noResultsText = text.replace(/(".*?") (.*)/, '$2 $1');
            },

            setNumberResults(text) {
                this.numberResults = text;
            },

            setNumberResultsUrl(text) {
                this.numberResultsUrl = text;
            },

            resetSearchData: function () {
                // Reinitialize Variables to avoid wrong search results.
                this.searchPages = [];
                this.searchPagesTotal = 0;
                this.searchCategories = [];
                this.searchCategoriesTotal = 0;
                this.searchProducts = [];
                this.searchProductsTotal = 0;
            },

            doSearch: function (query) {
                var self = this;
                // Min search length
                if (query.length < this.blockConfig.minSearchLength) {
                    this.showHotSearch();
                    this.isLoading = false;
                    this.hideSearchResults();
                    this.hideNoResults();

                    return;
                } else {
                    this.hideHotSearch();
                    this.isLoading = true;
                    this.showSearchResults();
                    this.hideNoResults();
                }

                // AJAX for searchautocomplete/ajax/suggest/
                if (this.xhttp) {
                    try {
                        this.xhttp.abort();
                    } catch {

                    }
                }
                this.xhttp = new XMLHttpRequest();
                var xhttp = this.xhttp;

                var queryEncoded = encodeURIComponent(query);
                var url = this.blockConfig.url.replace(/\/$/, "") + "/?q=" + queryEncoded + "&store_id=" + this.blockConfig.storeId + "&cat=false";

                xhttp.open("GET", url, true);
                xhttp.setRequestHeader("Content-Type", "application/json");

                xhttp.onreadystatechange = function () {
                    if (this.readyState === 4 && this.status === 200) {
                        // Response from ajax call in JSON.
                        var response = JSON.parse(this.responseText);

                        self.resetSearchData();

                        // Product Search Results
                        for (index in response.indexes) {

                            if (response.indexes[index].items.length > 0) {
                                var res = response.indexes[index];
                                var map = null;

                                if (self.searchMap[res.identifier]) {
                                    map = self.searchMap[res.identifier];
                                    self['search' + map] = res.items;
                                    self['search' + map + 'Total'] = res.totalItems;
                                }
                            }
                        }

                        self.isLoading = false;
                        self.hideNoResults();
                        self.setNumberResults(response.textAll);
                        self.setNumberResultsUrl(response.urlAll);

                        if (response.noResults) {
                            self.setNoResultsText(response.textEmpty);
                            self.hideSearchResults();
                            self.showNoResults();
                        }
                    }
                };
                xhttp.send();
            },

            canShowClearSearch() {
                return this.searchInput.length > 0;
            },

            clearSearch() {
                this.searchInput = '';
                this.hideSearchResults();
                this.hideNoResults();
                this.showHotSearch();
            },

            getCategoryName(nameHtml) {
                let nameElement = document.createElement('div');
                nameElement.innerHTML = nameHtml;

                let iconElementOriginal = nameElement.querySelector('i');

                if (!iconElementOriginal) {
                    return nameHtml;
                }

                let iconElement = document.createRange().createContextualFragment(this.categoryBreadcrumbsSeparator);

                iconElementOriginal.replaceWith(iconElement);

                return nameElement.innerHTML;
            },

            getNumberResults(numberResults) {
                return numberResults.replace('→', '');
            },

            calculatePositions() {
                const headerEl = document.getElementById('header');
                const rectHeader = headerEl.getBoundingClientRect();
                this.backdropTop = rectHeader.bottom;
                const searchInputEl = this.$refs.searchInput;
                const rectSearchInput = searchInputEl.getBoundingClientRect();
                this.panelMarginTop = rectHeader.bottom - rectSearchInput.bottom + 4;
            },

            backdropStyles() {
                return 'top: ' + this.backdropTop + 'px;' + (this.isOpen ? 'display: block;' : 'display: none;');
            },

            panelStyles() {
                return 'margin-top: ' + this.panelMarginTop + 'px;';
            }
        }
    }
</script>
