<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Review\Block\Product\ReviewRenderer;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;

/** @var ReviewRenderer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$rating = $block->getRatingSummary();
$ratingSteps = 5;

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

if (!$rating) {
    return '';
}
?>
<?php if ($block->isReviewEnabled()): ?>
    <div class="rating-summary flex gap-1 items-center">
        <div class="text-sm font-normal leading-5 text-primary">(<?= $escaper->escapeHtml(round($rating / 100 * $ratingSteps, 1)) ?>)</div>
        <?= $lucideIcons->renderHtml('star', $rating ? 'text-slate-900' : 'text-gray-200', 18, 18) ?>
    </div>
<?php endif; ?>
