<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist;
use Magento\Wishlist\Helper\Data as WishlistHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Wishlist $block */

$wishlistHelper = $this->helper(WishlistHelper::class);
?>

<?php if ($wishlistHelper->isAllow()): ?>
    <?= ($block->getChildHtml('wishlist.rss.link')) ?>
    <div class="form-wishlist-items">
        <?= $block->getChildHtml('top') ?>
        <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
        <?= $block->getChildHtml('items') ?>
        <?php if ($block->hasWishlistItems()): ?>
        <?php endif ?>
        <?= $block->getChildHtml('bottom') ?>
    </div>
<?php endif ?>
