<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

?>
<script>
    function initMessages() {
        "use strict";
        return {
            messages: window.mageMessages || [],
            typeNativeToToastMap: {
                'error': 'danger',
                'warning': 'warning',
                'notice': 'info',
                'success': 'success',
            },
            addMessages(messages) {
                // NOTE: use setTimeout to make sure the toast component is initialized after page content update
                setTimeout(() => {
                    messages.map((message) => {
                        this.showToastMessage(message);
                    });
                }, 0);
            },
            showToastMessage(message) {
                window.dispatchEvent(new CustomEvent('toast-show', {
                    detail: {
                        message: message.text,
                        type: this.typeNativeToToastMap[message.type] || 'default',
                    }
                }));
            },
            eventListeners: {
                ['@messages-loaded.window']() {
                    this.addMessages(event.detail.messages, event.detail.hideAfter)
                },
                ['@private-content-loaded.window'](event) {
                    const data = event.detail.data;
                    if (
                        data.messages &&
                        data.messages.messages &&
                        data.messages.messages.length
                    ) {
                        this.addMessages(data.messages.messages);
                    }
                },
                ['@clear-messages.window']() {
                    this.messages = [];
                }
            }
        }
    }
</script>

<?= $block->getChildHtml('markup') ?>
<?= $block->getChildHtml('logic') ?>
<?= $block->getChildHtml('item_logic') ?>
