<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Customer\Block\Account\Dashboard\Info;
use Magento\Framework\Escaper;

/** @var Info $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<h2 class="mb-6 text-2xl block-title">
    <?= $escaper->escapeHtml(__('Account Information')) ?>
</h2>
<div class="flex flex-wrap justify-between -m-4">
    <div class="w-full p-4 lg:w-1/2">
        <div class="flex flex-col h-full p-8 sm:flex-row card">
            <div
                class="inline-flex items-center justify-center shrink-0 w-16 h-16 mb-4
                    rounded-full sm:me-8 sm:mb-0 bg-gray-100">
                <?= $heroicons->userHtml('', 32, 32, ['aria-hidden' => 'true']) ?>
            </div>
            <div class="grow">
                <h3 class="mb-3 text-lg font-medium text-gray-900 title-font">
                    <span><?= $escaper->escapeHtml(__('Contact Information')) ?></span>
                </h3>
                <p>
                    <?= $escaper->escapeHtml($block->getName()) ?><br>
                    <?= $escaper->escapeHtml($block->getCustomer()->getEmail()) ?>
                </p>
                <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
                <a
                    class="inline-flex items-center w-full mt-3 md:text-sm"
                    href="<?= $escaper->escapeUrl($block->getUrl('customer/account/edit')) ?>"
                    aria-label="<?= $escaper->escapeHtml(__('Edit contact information')) ?>"
                >
                    <span><?= $escaper->escapeHtml(__('Edit')) ?></span>
                    <?= $heroicons->arrowRightHtml('ms-2', 16, 16, ['aria-hidden' => 'true']); ?>
                </a>
                <a
                    class="inline-flex items-center w-full md:text-sm"
                    href="<?= $escaper->escapeUrl($block->getChangePasswordUrl()) ?>"
                >
                    <?= $escaper->escapeHtml(__('Change Password')) ?>
                    <?= $heroicons->arrowRightHtml('ms-2', 16, 16, ['aria-hidden' => 'true']); ?>
                </a>
            </div>
        </div>
    </div>
    <?= $block->getChildHtml('additional_blocks'); ?>
</div>
