<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var Escaper $escaper */

/** @var Menu $block */

use Magento\Framework\Escaper;
use Snowdog\Menu\Block\Menu;

if (!$block->getMenu() || (int)$block->getLevel() !== 1) {
    return;
}

$parentNode = $block->getParentNode();
$parentNodeIndex = (int)$parentNode->getId();
$title = $parentNode->getTitle();
?>

<div id="submenu-<?= $parentNodeIndex ?>"
     x-ref="submenu-<?= $parentNodeIndex ?>"
     class="absolute top-full start-0 z-30 mt-0.5 w-64 max-h-96 overflow-y-auto py-2 px-1 rounded-md shadow-lg bg-white"
     x-show="isSubmenuOpened('<?= $parentNodeIndex ?>')"
     x-transition
     x-cloak
>
    <ul class="menu-list-2nd-level-dropdown w-full flex flex-col gap-1"
        title="Submenu for <?= $escaper->escapeHtmlAttr($title) ?>"
    >
        <?php foreach ($block->getSubmenuNodes() as $node): ?>
            <?php $nodeClasses = $node->getClasses(); ?>
            <li class="menu-list-item-2nd-level-dropdown <?= $escaper->escapeHtmlAttr($nodeClasses) ?>">
                <?= $block->renderMenuNode($node) ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
