<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */
declare(strict_types=1);

use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Catalog\Block\Product\View;
use Magento\Catalog\Helper\Image;

/**
 * @var View $block
 * @var Escaper $escaper
 * @var Product $product
 * @var string $addToCartBlock
 * @var Image $imageHelper
 */

$imageHelper = $this->helper(Image::class);
$image = $imageHelper->init($product, 'add_to_cart_panel_product');
?>

<?php if ($product->isSaleable()): ?>
    <div
        class="fixed-add-to-cart fixed bottom-0 inset-x-0 flex items-center pb-3 lg:pb-5 z-[49] transition-transform duration-200 ease-in-out transform"
        x-cloak
        x-data="initStickyAddToCartPanel"
        x-show="isSticky"
        x-transition:enter="translate-y-full"
        x-transition:enter-end="translate-y-0"
        x-transition:leave="translate-y-0"
        x-transition:leave-end="translate-y-full"
        @scroll.window.debounce.50ms="refreshState"
        @resize.window.debounce.50ms="refreshState"
    >
        <div class="bg-white mx-auto w-[calc(100%_-_10px)] py-[10px] px-[14px] md:px-[16px] lg:py-[8px] lg:px-[24px] flex items-center justify-between
                    sm:w-[calc(100%_-_30px)] xl:max-w-[1280px] 2xl:max-w-[1584px]
                    shadow-[0px_-2px_25px_-5px_rgba(0,0,0,0.10),-10px_20px_25px_-5px_rgba(12,16,94,0.12),-10px_10px_10px_-5px_rgba(17,23,142,0.05)] rounded-[20px]">
            <div class="hidden sm:flex items-center me-auto">
                <div class="me-[12px] lg:me-[22px] sm:w-[48px] lg:w-[80px]">
                    <img class="photo image product-image-photo"
                         src="<?= $escaper->escapeUrl($imageHelper->getUrl()) ?>"
                         width="<?= $image->getWidth() ?>"
                         height="<?= $image->getHeight() ?>"
                         loading="lazy"
                         alt="<?= $escaper->escapeHtml($block->stripTags($product->getName())) ?>"/>
                </div>
                <div class="sm:text-xs sm:font-medium sm:leading-4 lg:text-sm sm:me-[35px] line-clamp-2">
                    <?= $escaper->escapeHtml($product->getName()) ?>
                </div>
            </div>
            <div class="sm:me-[12px] lg:me-[24px]">
                <div>
                    <?= $block->getChildHtml("product.info.price") ?>
                </div>
            </div>
            <?php if ($addToCartBlock): ?>
                <?= $addToCartBlock
                    ->setData('container_css_base', 'qty-spinner-container relative w-full lg:w-[220px] h-10')
                    ->setData('container_css_additional', 'qty-spinner-container-add-to-cart-panel')
                    ->setData('form_id', 'product_addtocart_form_sticky')
                    ->setProduct($product)
                    ->toHtml(); ?>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
