<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Catalog\Helper\Output as CatalogOutputHelper;
use Magento\Catalog\Block\Product\View\Attributes;
use Magento\Catalog\Model\Product;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var CatalogOutputHelper $output */
/** @var Attributes $block */

/** @var CatalogOutputHelper $catalogOutputHelper */
$catalogOutputHelper = $this->helper(CatalogOutputHelper::class);

/** @var Product $product */
$product = $block->getProduct();

$getLayoutStyle = (string) $block->getLayoutStyle() ?: "";

$layoutStyleTableRow = $getLayoutStyle === "" ? "block lg:table-row" : ($getLayoutStyle === "list" ? "block" : "");
$layoutStyleTableCellHeading = $getLayoutStyle === ""
    ? "block lg:table-cell pt-3 lg:py-2 px-3"
    : ($getLayoutStyle === "list" ? "block pt-3 px-3" : "py-2 px-3");
$layoutStyleTableCellItem = $getLayoutStyle === ""
    ? "block lg:table-cell pb-3 lg:py-2 px-3"
    : ($getLayoutStyle === "list" ? "block pb-3 px-3" : "py-2 px-3");
?>

<?php if ($attributes = $block->getAdditionalData()): ?>
    <div class="table-wrapper overflow-x-auto" id="product-attributes">
        <div class="additional-attributes table-fixed w-full">
            <?php foreach ($attributes as $attribute): ?>
                <div class="flex text-sm font-normal leading-5">
                    <dt class="col label product-attribute-label text-start w-1/4 text-sm font-semibold leading-5 md:text-base md:leading-6 break-words hyphens-auto md:py-2"
                    ><?= $escaper->escapeHtml($attribute['label']) ?></dt>
                    <dd class="col data product-attribute-value text-start w-3/4 text-sm font-normal leading-5 md:text-base md:leading-6 text-slate-700 break-words hyphens-auto md:py-2"
                        data-th="<?= $escaper->escapeHtmlAttr($attribute['label']) ?>"
                    ><?= /* @noEscape */ $catalogOutputHelper->productAttribute($product, $attribute['value'], $attribute['code']) ?></dd>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif;?>
