<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;
use Magento\Catalog\Model\Product;
use Magento\Catalog\Model\Product\Option;
use Magento\Framework\Escaper;

/** @var View $block */
/** @var Escaper $escaper */

/** @var Product $product */
$product = $block->getProduct();

/**
 * Add to cart url is set on 'product.info' block by
 * @see \Magento\Checkout\Block\Cart\Item\Configure::_prepareLayout
 */
$productInfoBlock = $block->getLayout()->getBlock('product.info');
$productOptions = $product->getOptions() ?? [];
$hasMultiFormInputOption = (bool) array_filter($productOptions, fn($o) => $o->getType() === Option::OPTION_TYPE_FILE);

?>

<?php if ($product->isSaleable()): ?>
    <form method="post"
          action="<?= $escaper->escapeUrl($productInfoBlock->getSubmitUrl($product)) ?>"
          class="mb-6 max-lg:w-full"
          id="product_addtocart_form"
          <?php if ($hasMultiFormInputOption): ?> enctype="multipart/form-data"<?php endif; ?>
          <?php foreach ($block->getData('product_data_attributes') ?? [] as $attribute => $include): ?>
              <?php if ($include): ?>
                  <?= $escaper->escapeHtml(sprintf('data-%s', $attribute)); ?>="<?= $escaper->escapeHtmlAttr($product->getData($attribute)); ?>"
              <?php endif; ?>
          <?php endforeach; ?>
          x-data="{...initProductAddToCart(), ...hyva.formValidation($el)}"
          x-bind="eventListeners"
    >
        <input type="hidden" name="product" value="<?= (int)$product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value=""  />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <input type="hidden" name="item"  value="<?= (int)$block->getRequest()->getParam('id') ?>">
        <?= $block->getBlockHtml('formkey') ?>

        <?= $block->getChildHtml() ?>

    </form>
<?php endif; ?>
