<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $viewModels->require(ProductAttributes::class);
/** @var Product $product */
$product = $productViewModel->getProduct();
$productType = $product->getTypeId();

$addToCartBlock = $block->getChildBlock('add_to_cart');
$reviewHtml = trim($block->getChildHtml('product.info.review'));
?>
<div class="w-full mb-6">

    <div class="hidden md:block text-xs font-normal leading-4 mb-4">
        <span class="text-slate-700"><?= __('SKU:') ?> </span><span class="text-slate-500"><?= $product->getSku() ?></span>
    </div>

    <div role="group"
         aria-label="<?= $escaper->escapeHtmlAttr('Price') ?>"
         class="product-info-price mb-1">
        <?= $block->getChildHtml("product.info.price") ?>
    </div>

    <div class="flex mb-3 md:mb-5">
        <span class="flex text-sm font-normal leading-5 text-slate-700">
            <?= $block->getChildHtml("product.info.stockstatus") ?>
        </span>
        <?php if ($reviewHtml): ?>
            <span class="mx-1 text-sm text-slate-700">|</span>
            <?= $reviewHtml ?>
        <?php endif; ?>
    </div>

    <?php if ($shortDescription = $productViewModel->getShortDescription(false, false)) { ?>
        <div class="mb-4 product-description prose text-sm font-normal leading-5 text-slate-700">
            <?= /* @noEscape */ $shortDescription ?>
        </div>
    <?php } ?>

    <div class="static-add-to-cart flex gap-2">
        <?php if ($productType === 'bundle'): ?>
            <span class="sr-only">
                <?= $escaper->escapeHtml(__('The price depends on the chosen options')) ?>
            </span>
        <?php endif; ?>

        <?php if ($addToCartBlock): ?>
            <?= $addToCartBlock->setProduct($product)->toHtml(); ?>
        <?php else: ?>
            <?= $block->getChildHtml("product.info.quantity") ?>
            <?= $block->getChildHtml("product.info.form") ?>
        <?php endif; ?>
    </div>

    <?php if ($product->isSaleable() && $block->getChildHtml('addtocart.shortcut.buttons')): ?>
        <div class="flex mt-4 justify-end">
            <?= $block->getChildHtml('addtocart.shortcut.buttons') ?>
        </div>
    <?php endif; ?>

    <?php if ($additionalActions = $block->getChildHtml('product.info.additional.actions')): ?>
        <div class="flex gap-[14px] mt-3 mb-5 md:mb-4">
            <?= /** @noEscape */ $additionalActions; ?>
        </div>
    <?php endif; ?>

    <?php if($posAvailability = $block->getChildHtml("pos_availability")): ?>
        <div class="max-lg:my-2">
            <?= $posAvailability ?>
        </div>
    <?php endif; ?>

    <?php if ($tierPriceBlock = $block->getChildHtml("product.price.tier")): ?>
        <div class="py-4 my-2 tier-price-container">
            <?= /** @noEscape */ $tierPriceBlock ?>
        </div>
    <?php endif; ?>

    <?= $block->getChildHtml("mst_brand_product_page_logo") ?>

    <?= $block->getChildHtml("product.info.additional") ?>
</div>

<?php include($block->getTemplateFile('Magento_Catalog::product/view/add-to-cart-panel.phtml')) ?>
<?php include($block->getTemplateFile('Magento_Catalog::product/js/add-to-cart-panel.phtml')) ?>
