<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;

/** @var View $block */
/** @var Escaper $escaper */

/** @var Product $product */
$product = $block->getProduct();

/**
 * Add to cart url is set on 'product.info' block by
 * @see \Magento\Checkout\Block\Cart\Item\Configure::_prepareLayout
 */
$productInfoBlock = $block->getLayout()->getBlock('product.info');

?>

<?php if ($product->isSaleable()): ?>
    <form method="post"
          action="<?= $escaper->escapeUrl($productInfoBlock->getSubmitUrl($product)) ?>"
          id="product_addtocart_form" <?php if ($product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>
          x-data="{...initProductAddToCart(), ...hyva.formValidation($el)}"
          x-bind="eventListeners"
    >
        <input type="hidden" name="product" value="<?= (int)$product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value=""  />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <input type="hidden" name="item"  value="<?= (int)$block->getRequest()->getParam('id') ?>">
        <?= $block->getBlockHtml('formkey') ?>

        <?= $block->getChildHtml() ?>

    </form>
<?php endif; ?>
