<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var CurrentProduct $currentProduct */
$currentProduct = $viewModels->require(CurrentProduct::class);

/** @var Product $product */
$product = $currentProduct->get();

if (!$product->getId()) {
    return;
}
?>

<div class="text-right">
    <?php if ($product->getIsSalable()): ?>
        <p class="flex items-center justify-start align-middle available gap-x-2 stock"
           title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
            <span class="w-3 h-3 bg-green-500 rounded-full flex-shrink-0"></span>
            <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
        </p>
    <?php else: ?>
        <p class="flex items-center justify-start align-middle gap-x-2 unavailable stock"
           title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
            <span class="w-3 h-3 bg-red-500 rounded-full flex-shrink-0"></span>
            <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
        </p>
    <?php endif; ?>
</div>
