<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var StoreConfig $storeConfig */

$storeConfig = $viewModels->require(StoreConfig::class);
$defaultNotificationMessageTimeout = $storeConfig->getStoreConfig('hyva_theme_general/messages/success_message_timeout');
?>

<script>
    window.toast = function (message, options = {}) {
    }

    function initToasts() {
        return {
            dataFields: {
                'id': null,
                'message': null,
                'description': null,
                'type': 'default',
                'html': null
            },
            toasts: [],
            toastsHovered: false,
            expanded: false,
            layout: 'expanded',
            position: 'top-center',
            paddingBetweenToasts: 15,
            messageTimeout: <?= (int)$defaultNotificationMessageTimeout ?>,
            eventListeners: {
                ['@set-toasts-layout.window'](event) {
                    this.layout = event.detail.layout;
                    this.expanded = this.layout === 'expanded';

                    this.stackToasts();
                },

                ['@toast-show.window'](event) {
                    const options = this.buildOptions(event.detail);

                    this.toasts.unshift(options);
                },
                ['@mouseenter']() {
                    this.toastsHovered = true;
                },
                ['@mouseleave']() {
                    this.toastsHovered = false
                },
            },
            init() {
                if (this.layout === 'expanded') {
                    this.expanded = true;
                }
                this.stackToasts();
                this.$watch('toastsHovered', function (value) {
                    if (this.layout === 'default') {
                        if (this.position.includes('bottom')) {
                            this.resetBottom();
                        } else {
                            this.resetTop();
                        }
                        if (value) {
                            this.expanded = true;
                            if (this.layout === 'default') {
                                this.stackToasts();
                            }
                        } else {
                            if (this.layout === 'default') {
                                this.expanded = false;

                                this.stackToasts();

                                setTimeout(function () {
                                    this.stackToasts();
                                }.bind(this), 10)
                            }
                        }
                    }
                }.bind(this));
            },
            buildOptions(source) {
                let options = {};

                for (const dataField in this.dataFields) {
                    if (typeof source[dataField] != 'undefined') {
                        options[dataField] = source[dataField];
                    } else {
                        options[dataField] = this.dataFields[dataField];
                    }
                }

                if (typeof source.position != 'undefined') {
                    this.position = options.position;
                }

                options = Object.assign(options, {
                    id: 'toast-' + Math.random().toString(16).slice(2)
                });

                return options;
            },
            deleteToastWithId(id) {
                for (let i = 0; i < this.toasts.length; i++) {
                    if (this.toasts[i].id === id) {
                        this.toasts.splice(i, 1);
                        break;
                    }
                }
            },
            burnToast(id) {
                let burnToast = this.getToastWithId(id);
                let burnToastElement = document.getElementById(burnToast.id);
                if (burnToastElement) {
                    if (this.toasts.length === 1) {
                        if (this.layout === 'default') {
                            this.expanded = false;
                        }
                        burnToastElement.classList.remove('translate-y-0');
                        if (this.position.includes('bottom')) {
                            burnToastElement.classList.add('translate-y-full');
                        } else {
                            burnToastElement.classList.add('-translate-y-full');
                        }
                        burnToastElement.classList.add('-translate-y-full');
                    }
                    burnToastElement.classList.add('opacity-0');
                    let that = this;
                    setTimeout(function () {
                        that.deleteToastWithId(id);
                        setTimeout(function () {
                            that.stackToasts();
                        }, 1)
                    }, this.messageTimeout);
                }
            },
            getToastWithId(id) {
                for (let i = 0; i < this.toasts.length; i++) {
                    if (this.toasts[i].id === id) {
                        return this.toasts[i];
                    }
                }
            },
            stackToasts() {
                this.positionToasts();
                this.calculateHeightOfToastsContainer();
                let that = this;
                setTimeout(function () {
                    that.calculateHeightOfToastsContainer();
                }, 300);
            },
            positionToasts() {
                if (this.toasts.length === 0) return;
                let topToast = document.getElementById(this.toasts[0].id);
                topToast.style.zIndex = 100;
                if (this.expanded) {
                    if (this.position.includes('bottom')) {
                        topToast.style.top = 'auto';
                        topToast.style.bottom = '0px';
                    } else {
                        topToast.style.top = '0px';
                    }
                }
                if (this.toasts.length === 1) return;
                let middleToast = document.getElementById(this.toasts[1].id);
                middleToast.style.zIndex = 90;
                if (this.expanded) {
                    middleToastPosition = topToast.getBoundingClientRect().height +
                        this.paddingBetweenToasts + 'px';
                    if (this.position.includes('bottom')) {
                        middleToast.style.top = 'auto';
                        middleToast.style.bottom = middleToastPosition;
                    } else {
                        middleToast.style.top = middleToastPosition;
                    }
                    middleToast.style.scale = '100%';
                    middleToast.style.transform = 'translateY(0px)';
                } else {
                    middleToast.style.scale = '94%';
                    if (this.position.includes('bottom')) {
                        middleToast.style.transform = 'translateY(-16px)';
                    } else {
                        this.alignBottom(topToast, middleToast);
                        middleToast.style.transform = 'translateY(16px)';
                    }
                }
                if (this.toasts.length === 2) return;
                let bottomToast = document.getElementById(this.toasts[2].id);
                bottomToast.style.zIndex = 80;
                if (this.expanded) {
                    bottomToastPosition = topToast.getBoundingClientRect().height +
                        this.paddingBetweenToasts +
                        middleToast.getBoundingClientRect().height +
                        this.paddingBetweenToasts + 'px';
                    if (this.position.includes('bottom')) {
                        bottomToast.style.top = 'auto';
                        bottomToast.style.bottom = bottomToastPosition;
                    } else {
                        bottomToast.style.top = bottomToastPosition;
                    }
                    bottomToast.style.scale = '100%';
                    bottomToast.style.transform = 'translateY(0px)';
                } else {
                    bottomToast.style.scale = '88%';
                    if (this.position.includes('bottom')) {
                        bottomToast.style.transform = 'translateY(-32px)';
                    } else {
                        this.alignBottom(topToast, bottomToast);
                        bottomToast.style.transform = 'translateY(32px)';
                    }
                }
                if (this.toasts.length === 3) return;
                let burnToast = document.getElementById(this.toasts[3].id);
                burnToast.style.zIndex = 70;
                if (this.expanded) {
                    burnToastPosition = topToast.getBoundingClientRect().height +
                        this.paddingBetweenToasts +
                        middleToast.getBoundingClientRect().height +
                        this.paddingBetweenToasts +
                        bottomToast.getBoundingClientRect().height +
                        this.paddingBetweenToasts + 'px';
                    if (this.position.includes('bottom')) {
                        burnToast.style.top = 'auto';
                        burnToast.style.bottom = burnToastPosition;
                    } else {
                        burnToast.style.top = burnToastPosition;
                    }
                    burnToast.style.scale = '100%';
                    burnToast.style.transform = 'translateY(0px)';
                } else {
                    burnToast.style.scale = '82%';
                    this.alignBottom(topToast, burnToast);
                    burnToast.style.transform = 'translateY(48px)';
                }
                burnToast.firstElementChild.classList.remove('opacity-100');
                burnToast.firstElementChild.classList.add('opacity-0');
                let that = this;
                // Burn 🔥 (remove) last toast
                setTimeout(function () {
                    that.toasts.pop();
                }, 300);
                if (this.position.includes('bottom')) {
                    middleToast.style.top = 'auto';
                }
            },
            alignBottom(element1, element2) {
                // Get the top position and height of the first element
                let top1 = element1.offsetTop;
                let height1 = element1.offsetHeight;
                // Get the height of the second element
                let height2 = element2.offsetHeight;
                // Calculate the top position for the second element
                let top2 = top1 + (height1 - height2);
                // Apply the calculated top position to the second element
                element2.style.top = top2 + 'px';
            },
            alignTop(element1, element2) {
                // Get the top position of the first element
                let top1 = element1.offsetTop;
                // Apply the same top position to the second element
                element2.style.top = top1 + 'px';
            },
            resetBottom() {
                for (let i = 0; i < this.toasts.length; i++) {
                    if (document.getElementById(this.toasts[i].id)) {
                        let toastElement = document.getElementById(this.toasts[i].id);
                        toastElement.style.bottom = '0px';
                    }
                }
            },
            resetTop() {
                for (let i = 0; i < this.toasts.length; i++) {
                    if (document.getElementById(this.toasts[i].id)) {
                        let toastElement = document.getElementById(this.toasts[i].id);
                        toastElement.style.top = '0px';
                    }
                }
            },
            getBottomPositionOfElement(el) {
                return (el.getBoundingClientRect().height + el.getBoundingClientRect().top);
            },
            calculateHeightOfToastsContainer() {
                if (this.toasts.length === 0) {
                    this.$el.style.height = '0px';
                    return;
                }
                let lastToast = this.toasts[this.toasts.length - 1];
                let lastToastRectangle = document.getElementById(lastToast.id).getBoundingClientRect();
                let firstToast = this.toasts[0];
                let firstToastRectangle = document.getElementById(firstToast.id).getBoundingClientRect();
                if (this.toastsHovered) {
                    if (this.position.includes('bottom')) {
                        this.$el.style.height = ((firstToastRectangle.top + firstToastRectangle.height) - lastToastRectangle.top) + 'px';
                    } else {
                        this.$el.style.height = ((lastToastRectangle.top + lastToastRectangle.height) - firstToastRectangle.top) + 'px';
                    }
                } else {
                    this.$el.style.height = firstToastRectangle.height + 'px';
                }
            },
        }
    }
</script>
