<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\StoreConfig;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var StoreConfig $storeConfig */

$storeConfig = $viewModels->require(StoreConfig::class);
$defaultNotificationMessageTimeout = $storeConfig->getStoreConfig('hyva_theme_general/messages/success_message_timeout');
?>

<script>
    function initToastsItem() {
        return {
            toastHovered: false,
            init() {
                if (this.position.includes('bottom')) {
                    this.$el.firstElementChild.classList.add('toast-bottom');
                    this.$el.firstElementChild.classList.add('opacity-0', 'translate-y-full');
                } else {
                    this.$el.firstElementChild.classList.add('opacity-0', '-translate-y-full');
                }
                setTimeout(function () {
                    setTimeout(function () {
                        if (this.position.includes('bottom')) {
                            this.$el.firstElementChild.classList.remove('opacity-0', 'translate-y-full');
                        } else {
                            this.$el.firstElementChild.classList.remove('opacity-0', '-translate-y-full');
                        }
                        this.$el.firstElementChild.classList.add('opacity-100', 'translate-y-0');
                        setTimeout(function () {
                            this.stackToasts();
                        }.bind(this), 10);
                    }.bind(this), 5);
                }.bind(this), 50);
                setTimeout(function () {
                    this.$el.firstElementChild.classList.remove('opacity-100');
                    this.$el.firstElementChild.classList.add('opacity-0');
                    if (this.toasts.length === 1) {
                        this.$el.firstElementChild.classList.remove('translate-y-0');
                        this.$el.firstElementChild.classList.add('-translate-y-full');
                    }
                    setTimeout(function () {
                        this.deleteToastWithId(this.toast.id)
                    }.bind(this), 300);
                }.bind(this), <?= $defaultNotificationMessageTimeout ?>);
            },
            eventListeners: {
                ['@mouseover'](event) {
                    this.toastHovered = true
                },
                ['@mouseout'](event) {
                    this.toastHovered = false
                },
            }
        }
    }
</script>
