<?php
/** @var CustomUrl $block */

/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Snowdog\Menu\Block\NodeType\CustomUrl;

?>
<?php
$nodeId = $block->getId();
$imageUrl = $block->getImageUrl();
$imageAltText = $block->getImageAltText();
$imageWidth = $block->getImageWidth();
$imageHeight = $block->getImageHeight();
$content = $block->getContent();
$title = $block->getTitle();
$dataAttribute = 'data-menu="menu-' . $nodeId . '"';
$nodeClasses = $block->getNodeClasses();
$nodeId = $block->getId();
?>

<?php if ($content): ?>
    <a href="<?= $escaper->escapeUrl($content) ?>"
       class="snowdog-menu-link flex items-center gap-2 <?= $escaper->escapeHtmlAttr($nodeClasses) ?>"
       :class="{
           'text-primary': isSubmenuOpened('<?= $nodeId ?>')
       }"
        <?php if ($nodeId): ?>
            data-menu="menu-<?= $escaper->escapeHtmlAttr($nodeId) ?>"
        <?php endif; ?>
        <?php if ($block->getTarget()): ?>
            target="_blank"
            rel="noopener"
        <?php endif ?>
        <?= $dataAttribute ?>
    >
<?php else: ?>
    <span class="snowdog-menu-link flex items-center gap-2 <?= $escaper->escapeHtmlAttr($nodeClasses) ?>"
     <?= $dataAttribute ?>
    >
<?php endif; ?>
    <?php if ($imageUrl): ?>
        <img class=""
             src="<?= $escaper->escapeUrl($imageUrl) ?>"
             alt="<?= $escaper->escapeHtmlAttr($imageAltText) ?>"
             loading="lazy"
             width="<?= $escaper->escapeHtmlAttr($imageWidth) ?>"
             height="<?= $escaper->escapeHtmlAttr($imageHeight) ?>"
        />
    <?php endif; ?>
    <?= $escaper->escapeHtml($title) ?>
<?php if ($content): ?>
    </a>
<?php else: ?>
    </span>
<?php endif ?>
