<?php
/** @var Product $block */

/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Snowdog\Menu\Block\NodeType\Product;

?>
<?php
$nodeId = $block->getId();
$productUrl = $block->getProductUrl($nodeId);
$productUrl = $productUrl ?: '#';
$title = $block->getTitle();
$nodeClasses = $block->getNodeClasses();
$level = (int)$block->getLevel();

$imageSize = $imageWidth = $imageHeight = '300';
$imageUrl = $block->getResizedProductImage($nodeId, $imageWidth, $imageHeight);
$imageAltText = $block->getImageAltText();

if (!$imageUrl) {
    $imageUrl = $block->getImageUrl();
    $imageAltText = $block->getImageAltText();
    $imageWidth = $block->getImageWidth();
    $imageHeight = $block->getImageHeight();
}

if ($level === 0) {
    $linkClasses = 'snowdog-menu-link level-0 block py-2 px-1 rounded aria-[current=page]:font-medium';
} else {
    $startPadding = $level >= 2 ? 'ps-6' : 'ps-4';
    $linkClasses = "snowdog-menu-link py-3 leading-6 {$startPadding} pe-5 hover:bg-gray-100 aria-[current=page]:font-medium flex-1 min-w-0";
    $linkClasses .= $imageUrl ? ' flex items-center gap-2' : ' block';
}
$linkClasses .= $nodeClasses ? ' ' . $nodeClasses : '';
?>

<a href="<?= $escaper->escapeUrl($productUrl) ?>"
   class="<?= $escaper->escapeHtmlAttr($linkClasses) ?>"
    <?php if ($nodeId): ?>
        data-menu="menu-<?= $escaper->escapeHtmlAttr($nodeId) ?>"
    <?php endif; ?>
>
    <?php if ($imageUrl): ?>
        <img class=""
             src="<?= $escaper->escapeUrl($imageUrl) ?>"
             alt="<?= $escaper->escapeHtmlAttr($imageAltText) ?>"
             loading="lazy"
             width="<?= $escaper->escapeHtmlAttr($imageWidth) ?>"
             height="<?= $escaper->escapeHtmlAttr($imageHeight) ?>"
        />
    <?php endif; ?>
    <?= $escaper->escapeHtml($title) ?>
</a>
