<?php
/** @var Product $block */

/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Snowdog\Menu\Block\NodeType\Product;

?>
<?php
$nodeId = $block->getId();
$productUrl = $block->getProductUrl($nodeId);
$productUrl = $productUrl ?: '#';
$title = $block->getTitle();
$nodeClasses = $block->getNodeClasses();
$nodeId = $block->getId();

$imageSize = $imageWidth = $imageHeight = '300';
$imageUrl = $block->getResizedProductImage($nodeId, $imageWidth, $imageHeight);
$imageAltText = $block->getImageAltText();

if (!$imageUrl) {
    $imageUrl = $block->getImageUrl();
    $imageAltText = $block->getImageAltText();
    $imageWidth = $block->getImageWidth();
    $imageHeight = $block->getImageHeight();
}
?>

<a href="<?= $escaper->escapeUrl($productUrl) ?>"
   class="snowdog-menu-link flex items-center gap-2 <?= $escaper->escapeHtmlAttr($nodeClasses) ?>"
   :class="{
       'text-primary': isSubmenuOpened('<?= $nodeId ?>')
   }"
    <?php if ($nodeId): ?>
        data-menu="menu-<?= $escaper->escapeHtmlAttr($nodeId) ?>"
    <?php endif; ?>
>
    <?php if ($imageUrl): ?>
        <img class=""
             src="<?= $escaper->escapeUrl($imageUrl) ?>"
             alt="<?= $escaper->escapeHtmlAttr($imageAltText) ?>"
             loading="lazy"
             width="<?= $escaper->escapeHtmlAttr($imageWidth) ?>"
             height="<?= $escaper->escapeHtmlAttr($imageHeight) ?>"
        />
    <?php endif; ?>
    <?= $escaper->escapeHtml($title) ?>
</a>
