<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var $block \Mirasvit\Brand\Block\Widget\BrandSlider */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */
/** @var \Hyva\Theme\ViewModel\Slider $sliderViewModel */

$sliderViewModel = $viewModels->require(\Hyva\Theme\ViewModel\Slider::class);
$itemsTemplate   = 'Mirasvit_Brand::widget/brand_slider_item.phtml';
$items           = $block->getSliderItems(); // a collection or array of items to render
?>
<?php
$itemsLimit             = $block->getItemsLimit();
$sliderItems            = $block->getSliderItems();
$isShowTitle            = $block->isShowTitle();
$titleText              = $block->getTitleText();
$titleTextColor         = $block->getTitleTextColor();
$titleBackgroundColor   = $block->getTitleBackgroundColor();
$isShowBrandLabel       = $block->isShowBrandLabel();
$brandLabelColor        = $block->getBrandLabelColor();
$isShowButton           = $block->isShowButton();
$isShowPagination       = $block->isShowPagination();
$isAutoPlay             = $block->isAutoPlay();
$autoPlayInterval       = $block->getAutoPlayInterval();
$isAutoPlayLoop         = $block->isAutoPlayLoop();
$sliderWidth            = $block->getSliderWidth();
$sliderImageWidth       = $block->getSliderImageWidth();
$spacingBetweenImages   = $block->getSpacingBetweenImages();
$pauseOnHover           = $block->getPauseOnHover();
$inactivePagingColor    = $block->getInactivePagingColor();
$activePagingColor      = $block->getActivePagingColor();
$hoverPagingColor       = $block->getHoverPagingColor();
$navigationButtonsColor = $block->getNavigationButtonsColor();

$items = array_slice($items, 0, $itemsLimit);

$containerId = 'mst-brand__slider-' . rand(10000, 100000);
$sliderView = $sliderViewModel->getSliderForItems($itemsTemplate, $items, 'Mirasvit_Brand::widget/brand_slider_slider.phtml');

if ($block->isShowTitle()) {
    $sliderView->setData('title', $block->getTitleText());

}

// pass autoplay config
$sliderView->setData('is_autoplay', $isAutoPlay)
    ->setData('autoplay_interval', $autoPlayInterval)
    ->setData('is_autoplay_loop', $isAutoPlayLoop)
    ->setData('pause_on_hover', $pauseOnHover)
    ->setData('is_show_button', $isShowButton)
    ->setData('is_show_pagination', $isShowPagination);
?>

<style>
    .<?=$containerId ?> .js_slides .js_slide, .<?=$containerId ?> .js_slides .js_dummy_slide {
        width: <?= $itemsLimit < 6 ? round(100 / $itemsLimit, 3) : 16.666?>%;
    }

    <?php if ($titleTextColor): ?>
    .<?=$containerId ?> h3 {
        color: <?= $titleTextColor ?>;
    }
    <?php endif; ?>

    .<?=$containerId ?> .container {
    <?php if ($titleBackgroundColor): ?>
        background-color: <?= $titleBackgroundColor ?>;
    <?php endif; ?>
    }

    <?php if (!$isShowButton): ?>
    .<?=$containerId ?> button[aria-label="Previous"], .<?=$containerId ?> button[aria-label="Next"] {
        display: none;
    }
    <?php endif; ?>

    <?php if (!$isShowBrandLabel): ?>
    .<?=$containerId ?> .m-brand-label {
        display: none;
    }
    <?php endif; ?>

    <?php if ($brandLabelColor): ?>
    .<?=$containerId ?> .js_slides .m-brand-label a {
        color: <?= $brandLabelColor ?>;
    }
    <?php endif ?>

    <?php if ($sliderWidth): ?>
    .<?=$containerId ?> section {
        max-width: <?= $sliderWidth ?>px;
        margin-left: auto;
        margin-right: auto;
    }
    <?php endif ?>

    .<?=$containerId ?> section .js_slides img {
        margin: auto;
    <?php if ($sliderImageWidth): ?>
        width: <?= $sliderImageWidth ?>px;
    <?php endif ?>
    }


    <?php if ($navigationButtonsColor): ?>
    .<?=$containerId ?> button[aria-label="Previous"], .<?=$containerId ?> button[aria-label="Next"] {
        color: <?= $navigationButtonsColor ?>;
    }
    .<?=$containerId ?> button[aria-label="Previous"]._inactive, .<?=$containerId ?> button[aria-label="Next"]._inactive {
        opacity: 0.5;
    }
    <?php endif; ?>

    <?php if ($inactivePagingColor): ?>
    .<?=$containerId ?>>section>div>div:last-child>div>div span {
        background: <?= $inactivePagingColor ?>;
    }

    <?php endif ?>

    <?php if ($activePagingColor): ?>
    .<?=$containerId ?>>section>div>div:last-child>div>div span._active {
        background: <?= $activePagingColor ?>;
    }

    <?php endif ?>

    <?php if ($hoverPagingColor): ?>
    .<?=$containerId ?>>section>div>div:last-child>div>div span:hover {
        background: <?= $hoverPagingColor ?>;
    }

    <?php endif; ?>
</style>

<div class="<?= $containerId ?> m-brand-slider-container">
    <?= $sliderView->toHtml() ?>
</div>
