<?php

/** @var Escaper $escaper */
/** @var Menu $block */

use Magento\Framework\Escaper;
use Snowdog\Menu\Block\Menu;

?>
<?php if ($block->getMenu()): ?>
    <?php
    $parentNode = $block->getParentNode();
    $parentNodeIndex = $parentNode->getId();
    $level = (int)$block->getLevel();
    $title = $parentNode->getTitle();
    ?>
    <?php if ($level === 1): ?>
        <div
            x-ref="submenu-<?= /* @noEscape */ (string) $parentNodeIndex ?>"
            class="absolute top-full w-screen z-30 border-t border-t-slate-100 shadow-md bg-white flex rtl:start-1/2 ltr:end-1/2 translate-x-1/2"
            x-show="isSubmenuOpened('<?= (string)$parentNodeIndex ?>')"
            x-transition:enter="transition ease-out duration-300 delay-300"
            x-transition:enter-start="opacity-0"
            x-transition:enter-end="opacity-100"
            x-cloak
        >
            <div class="w-full">
                <ul
                    class="container flex flex-wrap justify-between items-start gap-x-[5%] py-6 menu-list menu-list-level-1"
                >
                    <?php foreach ($block->getSubmenuNodes() as $node): ?>
                        <?php
                        $childrenLevel = $node->getLevel() + 1;
                        $children = $block->getNodes($childrenLevel, $node);
                        $node->setIsParent((bool) $children);
                        $nodeType = $node->getType();
                        $nodeClasses = $node->getClasses();
                        ?>
                        <li class="menu-list-item menu-list-item-level-1 flex-1 <?= $escaper->escapeHtmlAttr($nodeClasses) ?>">
                            <div class="group level-1">
                                <?= /* @noEscape */ $block->renderMenuNode($node) ?>
                            </div>
                            <?= /* @noEscape */ $block->renderSubmenu($children, $node, $childrenLevel) ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($level > 1): ?>
        <ul class="menu-list menu-list-level-<?= $level + 1 ?>">
            <?php foreach ($block->getSubmenuNodes() as $index => $node): ?>
                <?php
                $childrenLevel = $node->getLevel() + 1;
                $children = $block->getNodes($childrenLevel, $node);
                $node->setIsParent((bool) $children);
                $nodeType = $node->getType();
                $nodeClasses = $node->getClasses();
                ?>
                <li class="menu-list-item menu-list-item-level-<?= $childrenLevel + 1 ?> <?= $escaper->escapeHtmlAttr($nodeClasses) ?>">
                    <?= /* @noEscape */ $block->renderMenuNode($node) ?>
                    <?= /* @noEscape */ $block->renderSubmenu($children, $node, $childrenLevel) ?>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
<?php endif; ?>
