<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var LucideIcons $lucideIcons */

$lucideIcons = $viewModels->require(LucideIcons::class);
?>

<div class="carousel-nav">
    <div class="swiper-pagination invisible"></div>
    <div class="swiper-button-prev invisible">
        <?= $lucideIcons->arrowLeftHtml('rtl:-rotate-180', 18, 18, ['aria-hidden' => 'true']); ?>
    </div>
    <div class="swiper-button-next invisible">
        <?= $lucideIcons->arrowRightHtml('rtl:-rotate-180', 18, 18, ['aria-hidden' => 'true']); ?>
    </div>
</div>
