<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Magento\Framework\Escaper;
use Snowdog\Menu\Block\Menu;

/** @var Menu $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

$menu = $block->getMenu();
$uniqueId = '_' . uniqid();
?>

<?php if ($menu): ?>
    <script>
        'use strict';

        const initTopmenuDesktop<?= $escaper->escapeHtml($uniqueId) ?> = () => ({
            openSubmenuId: null,
            openSubItemIds: [],
            toggleSubmenu(show, menuNode) {
                if (show === false || menuNode === this.openSubmenuId) {
                    this.openSubmenuId = null;
                    this.openSubItemIds = [];
                    hyva.releaseFocus();
                } else {
                    this.openSubmenuId = menuNode;
                    this.openSubItemIds = [];
                }
            },
            toggleSubmenuClick(menuNode) {
                this.openSubmenuId = this.openSubmenuId === menuNode ? null : menuNode;
                this.openSubItemIds = [];
                if (this.openSubmenuId === null) {
                    hyva.releaseFocus();
                }
            },
            toggleSubItem(menuNode) {
                const index = this.openSubItemIds.indexOf(menuNode);
                if (index === -1) {
                    this.openSubItemIds.push(menuNode);
                } else {
                    this.openSubItemIds.splice(index, 1);
                }
            },
            canHover() {
                return window.matchMedia('(hover: hover) and (pointer: fine)').matches;
            },
            onSubmenuEscape(event) {
                event.stopPropagation()
                this.$refs['sr-button-' + this.openSubmenuId]?.focus()
                this.toggleSubmenu(false);
            },
            isSubmenuOpened(node) {
                return this.openSubmenuId === node;
            },
            isSubItemOpened(node) {
                return this.openSubItemIds.includes(node);
            },

        })
    </script>

    <div x-data="initTopmenuDesktop<?= $escaper->escapeHtml($uniqueId) ?>()"
         class="navigation z-20 hidden lg:flex lg:justify-center <?= $escaper->escapeHtmlAttr($menu->getCssClass()) ?>"
         @click.outside="toggleSubmenu(false)"
    >
        <div class="hidden lg:block lg:px-8">
            <nav
                class="snowdog-topmenu-desktop relative"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>"
            >
                <ul class="menu-list menu-list-level-0 flex justify-start flex-wrap gap-x-7 py-4">
                    <?php foreach ($block->getNodes() as $node): ?>
                        <?php
                        $childrenLevel = $node->getLevel() + 1;
                        $children = $block->getNodes($childrenLevel, $node);
                        $node->setIsParent((bool)$children);
                        $nodeId = (string)$node->getId();
                        $title = $node->getTitle();
                        $nodeType = $node->getType();
                        $nodeClasses = $node->getClasses();
                        ?>
                        <li class="menu-list-item menu-list-item-level-0 relative flex items-center border-b-2 border-transparent hover:border-primary <?= $escaper->escapeHtmlAttr($nodeClasses) ?>"
                            :class="{ 'border-primary': isSubmenuOpened('<?= $nodeId ?>') }"
                            @mouseenter="canHover() && toggleSubmenu(true, '<?= $nodeId ?>')"
                            @mouseleave="canHover() && toggleSubmenu(false)"
                            @keydown.escape="onSubmenuEscape"
                        >
                            <?= $block->renderMenuNode($node) ?>
                            <?php if ($children): ?>
                                <button
                                    type="button"
                                    class="group rounded p-1"
                                    x-ref="sr-button-<?= $nodeId ?>"
                                    aria-expanded="false"
                                    :aria-expanded="isSubmenuOpened('<?= $nodeId ?>')"
                                    aria-controls="submenu-<?= $nodeId ?>"
                                    @click="toggleSubmenuClick('<?= $nodeId ?>')"
                                >
                                    <?= $lucideIcons->renderHtml(
                                        'chevron-down',
                                        'transition-transform group-aria-expanded:rotate-180',
                                        20,
                                        20,
                                        ['aria-hidden' => 'true']
                                    ) ?>
                                    <span class="sr-only">
                                        <?= $escaper->escapeHtml(__('Toggle submenu for %1', $title)) ?>
                                    </span>
                                </button>
                            <?php endif; ?>
                            <?= /* @noEscape */
                            $block->renderSubmenu($children, $node, $childrenLevel) ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </nav>
        </div>
    </div>
<?php endif; ?>
