<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/**
 * @var $block \Mirasvit\LayeredNavigation\Block\Css
 */
$css = $block->getCss();

?>
<?php if ($css): ?>
    <style><?= $css ?></style>
<?php endif ?>


<style>
    [data-element="filter"][data-hidden=true],
    [data-element="filter"][data-search-hidden=true],
    [data-element="filter"][data-letter-hidden=true] {
        display: none !important;
    }

    .mst-nav__horizontal-bar .block-title {
        display: none;
    }

    .mst-nav__horizontal-bar>[x-data="initLayeredNavigation()"] {
        margin: 0;
    }

    .mst-nav__horizontal-bar .block-content {
        display: flex;
        flex-wrap: wrap;
    }

    .mst-nav__horizontal-bar .block-content .filter-option {
        position: relative;
    }

    .mst-nav__horizontal-bar .block-content .filter-options-content {
        position: absolute;
        width: max-content;
        background-color: #fff;
        right: 0;
        z-index: 1;
    }

    .mst-nav__horizontal-bar .block-content .mst-nav__search-suggestion {
        max-height: 600px;
        overflow-y: auto;
    }

    .mst-nav__horizontal-bar .block-content .mst-nav__search-suggestion .filter-options-content {
        position: relative;
        width: 100%;
        padding: 0;
        box-shadow: none;
    }

    @media screen and (max-width: 767px){
        .mst-nav__horizontal-bar .block-content {
            padding: 0;
            position: relative;
        }

        .mst-nav__horizontal-bar .block-content .filter-option,
        .mst-nav__horizontal-bar .block-content .filter-current {
            margin: .125rem;
            position: static;
        }

        .mst-nav__horizontal-bar .block-content .filter-options-content {
            width: auto;
            right: .125rem;
            left: .125rem;
        }
    }
</style>
