<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Mirasvit\LayeredNavigation\Model\Config\ExtraFilterConfigProvider;
use Hyva\Theme\ViewModel\LucideIcons;

/**
 * @var $block \Mirasvit\LayeredNavigation\Block\Renderer\SearchRenderer
 * @var $escaper \Magento\Framework\Escaper
 * @var \Hyva\Theme\Model\ViewModelRegistry $viewModels
 */

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);
$attributeCode = $block->getAttributeCode();
?>

<div class="mst-nav__label mst-nav__search" data-mst-nav-filter="search" id="mst-nav__search" x-data="{...initLabelRenderer(), ...initSearchRenderer()}" x-init="initSearch()">
    <div class="mst-nav__search-field">
        <div class="mst-nav__search-wrapper">
            <label for="mst-nav__search-filter"></label>
            <input
                    type="text"
                    class="form-input rounded-lg w-full text-sm placeholder-[#909192] py-[9px]"
                    name="<?= ExtraFilterConfigProvider::SEARCH_FILTER_FRONT_PARAM ?>"
                    placeholder="<?= $block->getFilter()->getName() ?>"
                    id="mst-nav__search-filter"
                    autocomplete="off"
                    @click="isSearchFocused = true"
                    @click.outside="isSearchFocused = false"
            >
            <a id="mst-nav__search-apply" href="" class="action search" data-element="filter" @click="handleClick">
                <?= $lucideIcons->renderHtml(
                    'search',
                    "hover:text-black",
                    19,
                    19,
                    [
                        ':class' => "{'text-[#225ee7]': isSearchFocused, 'text-current': !isSearchFocused}",
                        'aria-hidden' => 'true'
                    ]
                ) ?>
            </a>
        </div>
        <div x-data="{isSearchSuggestion: true}" class="mst-nav__search-suggestion pt-[19px]" id="mst-nav__search-suggestion" style="display: none"></div>
    </div>

    <ol class="items">
        <?php foreach ($block->getAppliedSearchTerms() as $term): ?>
            <div class="filter-current">
                <li data-element="filter" class="mst-nav__state-filter item _checked _highlight">
                    <span class="filter-value"><?= $term['label'] ?></span>
                    <a class="mst-nav__search-term action remove" href="<?= $term['url'] ?>" @click="handleClick">X</a>
                </li>
            </div>
        <?php endforeach; ?>
    </ol>
</div>

<style>
    .sidebar-main .filter-options .filter-options-item:first-child .filter-options-content {
        display: block!important;
    }

    .sidebar-main .filter-options .filter-options-item:first-child .filter-options-title {
        display: none!important;
    }

    .mst-nav__search-suggestion {
        background: white;
    }

    .mst-nav__search-suggestion .filter-options-title {
        display: block!important;
    }

    <?php if ($block->isHighlightEnabled()): ?>
    .mst-nav__search .mst-nav__state-filter {
        color: <?= $block->getHighlightColor() ?>;
    }
    <?php endif; ?>

    <?php if (!$block->isUseFulltext()): ?>
    #mst-nav__search-apply {
        display: none;
    }
    <?php endif; ?>

    .mst-nav__search-wrapper {
        position: relative;
    }

    .mst-nav__search-field #mst-nav__search-filter {
        padding-right: 26px;
        margin-left: auto;
        margin-right: auto;
    }

    .mst-nav__search-field #mst-nav__search-apply {
        position: absolute;
        left: 16px;
        top: 11px;
        background: #fff;
    }

    .mst-nav__suggest-match {
        color: cornflowerblue;
    }
</style>
