<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\ProductAttributes as ProductAttributes;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

/** @var Product $product */
if (! ($product = $block->getData('product'))) {
    return;
}

$productId = $product->getId();

$productAttribute = $viewModels->require(ProductAttributes::class);
$productName = $productAttribute->getValue($product, 'name');

?>

<button x-data="initWishlist()"
        x-defer="intersect"
        @click.prevent="addToWishlist(<?= (int) $productId ?>)"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List') . ' ' . $productName) ?>"
        type="button"
        class="rounded-full w-8 h-8 inline-flex shrink-0 items-center justify-center text-slate-500 bg-slate-200 hover:text-primary hover:bg-slate-100"
        data-addto="wishlist"
>
    <?= $lucideIcons->heartHtml( '', 16, 16, ['aria-hidden' => 'true']) ?>
</button>
