<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Escaper $escaper */
/** @var Toolbar $block */
/** @var ViewModelRegistry $viewModels */
/** @var SvgIcons $icons */

$uniqueId = '_' . uniqid();
$additionalOptions = ['page' => 'p'];
$icons = $viewModels->require(SvgIcons::class);
?>
<script>
    function initToolbar<?= /** @noEscape */  $uniqueId ?>() {
        return {
            options: <?= /* @noEscape */ $block->getWidgetOptionsJson($additionalOptions) ?>.productListToolbarForm || {},
            getUrlParams: function () {
                let decode = window.decodeURIComponent,
                    urlPaths = this.options.url.split('?'),
                    urlParams = urlPaths[1] ? urlPaths[1].split('&') : [],
                    params = {},
                    parameters, i;

                for (i = 0; i < urlParams.length; i++) {
                    parameters = urlParams[i].split('=');
                    params[decode(parameters[0])] = parameters[1] !== undefined ?
                        decode(parameters[1].replace(/\+/g, '%20')) :
                        '';
                }

                return params;
            },
            getCurrentLimit: function () {
                return this.getUrlParams()[this.options.limit] || this.options.limitDefault;
            },
            getCurrentPage: function () {
                return this.getUrlParams()[this.options.page] || 1;
            },
            changeUrl(paramName, paramValue, defaultValue) {
                let urlPaths = this.options.url.split('?'),
                    baseUrl = urlPaths[0],
                    paramData = this.getUrlParams(),
                    currentPage = this.getCurrentPage(),
                    newPage;

                /**
                 * calculates the page on which the first item of the current page will
                 * be with the new limit and sets that number as the new page
                 */
                if (currentPage > 1 && paramName === this.options.limit) {
                    newPage = Math.floor(this.getCurrentLimit() * (currentPage - 1) / paramValue) + 1;

                    if (newPage > 1) {
                        paramData[this.options.page] = newPage;
                    } else {
                        delete paramData[this.options.page];
                    }
                }

                paramData[paramName] = paramValue;

                if (this.options.post) {
                    hyva.postForm({action: baseUrl, data: paramData, skipUenc: true});
                } else {
                    if (paramValue === defaultValue.toString()) {
                        delete paramData[paramName];
                    }
                    paramData = Object.keys(paramData).length === 0
                        ? ''
                        : '?' + (new URLSearchParams(paramData));
                    location.href = baseUrl + paramData
                }
            }
        }
    }
</script>

<script>
    function filterCountUpdater() {
        return {
            filterCount: 0,
            updateFilterCount() {
                const stateElement = document.getElementById('state-top');
                if (!stateElement) return;
                const olElement = stateElement.querySelector("ol.items");
                if (olElement) {
                    this.filterCount = olElement.querySelectorAll("li").length - 1;
                } else {
                    this.filterCount = 0;
                }
            },
            init() {
                this.updateFilterCount();
                const stateElement = document.getElementById('state-top');
                if (!stateElement) return;
                const observer = new MutationObserver(() => {
                    this.updateFilterCount();
                });
                observer.observe(stateElement, {childList: true, subtree: true});
            }
        }
    }
</script>

<div class="toolbar-wrapper flex w-full">
    <?php if ($block->getCollection()->getSize()): ?>
        <div x-data="initToolbar<?= /** @noEscape */ $uniqueId ?>()" class="toolbar toolbar-products <?= !$block->getIsBottom() ? 'toolbar-top' : '' ?> mb-2 lg:mb-4 flex flex-wrap max-lg:gap-y-2">
            <div class="w-full flex flex-row">
                <div class="w-full">
                    <?php if ($block->getIsBottom()): ?>
                        <?= /** @noEscape */  $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
                        <?= $block->getPagerHtml() ?>
                        <?= /** @noEscape */ $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
                    <?php else: ?>
                        <?php if ($block->isExpanded()): ?>
                            <?= /** @noEscape */ $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
                            <?= /** @noEscape */ $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
                        <?php endif ?>
                    <?php endif ?>
                </div>
            </div>
        </div>
    <?php endif ?>
    <?php if (!$block->getIsBottom()): ?>
        <div class="horizontal-filters">
            <?= $block->getChildHtml('m.horizontal.navigation.container') ?>
        </div>
        <div class="all-filters-btn">
            <button @click="$dispatch('toggle-layered-nav', { isOpen: true })" class="btn filter-dropdown-button">
                <?= $escaper->escapeHtml(__('Shop By')) ?>
                <?= $icons->adjustmentsHorizontalHtml('h-4 w-4'); ?>
            </button>
        </div>
    <?php endif ?>
</div>

<?php if (!$block->getIsBottom()): ?>
    <div>
        <?= $block->getLayout()->getBlock('m.catalog.navigation.horizontal.state')->toHtml(); ?>
    </div>
<?php endif ?>
