<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Catalog\Block\Product\View;
use Magento\Framework\Escaper;

/** @var View $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$product = $block->getProduct();
$is3Col = ($product->getData('page_layout') === '3columns');
?>
<?php if ($is3Col): ?>



    <?= $block->getChildHtml('product.title') ?>

    <div class="product-3col-grid">

        <div class="product-3col-one">
            <?= $block->getChildHtml('product.media') ?>
        </div>

        <div class="product-3col-two">
            <div class="flex sku text-sm font-normal leading-5">
                <dt class="product-detail-label w-2/5 text-start text-slate-500 py-2"><?= __('SKU:') ?> </dt>
                <dd class="product-detail-value w-3/5 ms-2 text-start text-slate-700 py-2"><?= $escaper->escapeHtml($product->getSku()) ?></dd>
            </div>
            <?php
            $featuredAttrsBlock = $block->getLayout()->getBlock('product.attributes.featured');
            if ($featuredAttrsBlock) {
                echo $featuredAttrsBlock->toHtml();
                $block->getLayout()->unsetElement('product.attributes.featured');
            }
?>
            <?php
            /** @var ProductPage $productViewModel */
            $productViewModel = $viewModels->require(ProductPage::class);
            if ($shortDescription = $productViewModel->getShortDescription(false, false)):
            ?>
                <div class="mb-4 mt-2 product-description prose text-sm font-normal leading-5 text-slate-700">
                    <?= /* @noEscape */ $shortDescription ?>
                </div>
            <?php endif; ?>
        </div>

        <div class="product-3col-three">
            <?php
            $productInfoBlock = $block->getChildBlock('product.info');
            if ($productInfoBlock) {
                $productInfoBlock->setData('hide_featured_attrs', true);
                $productInfoBlock->setData('hide_short_description', true);
                echo $productInfoBlock->toHtml();
                $productInfoBlock->unsetData('hide_short_description');
            }
            ?>
        </div>

    </div>

    <section>
        <?= $block->getChildHtml('product_options_wrapper_bottom') ?>
    </section>

    <?= $block->getChildHtml('product.info.details') ?>

    <section>
        <?= $block->getChildHtml('related') ?>
        <?= $block->getChildHtml('upsell') ?>
        <?= $block->getChildHtml('review_list') ?>
        <?= $block->getChildHtml('review_form') ?>
    </section>
<?php else: ?>

<section class="flex flex-col md:flex-row md:gap-4 lg:gap-4 2xl:gap-11">
    <h1 class="md:hidden text-2xl font-bold leading-6 text-slate-700 mb-1">
        <?= $escaper->escapeHtml($product->getName()) ?>
    </h1>

    <div class="md:hidden text-xs font-normal leading-4 mb-5">
            <span class="text-slate-700"><?= __('SKU:') ?> </span>
            <span class="text-slate-500"><?= $escaper->escapeHtml($product->getSku()) ?></span>
    </div>

    <div class="w-full md:w-1/2">
        <?= $block->getChildHtml('product.media') ?>
    </div>
    <div class="w-full md:w-1/2">
        <div class="hidden md:block">
            <?= $block->getChildHtml('product.title') ?>
        </div>
        <?= $block->getChildHtml('product.info') ?>
    </div>
</section>

<section>
    <?= $block->getChildHtml('product_options_wrapper_bottom') ?>
</section>

    <?= $block->getChildHtml('product.info.details') ?>

<section>
    <?= $block->getChildHtml('related') ?>
    <?= $block->getChildHtml('upsell') ?>
    <?= $block->getChildHtml('review_list') ?>
    <?= $block->getChildHtml('review_form') ?>
</section>
<?php endif; ?>
