<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

// @tailwind 'animate-spin'
?>
<div
    class="z-50 fixed inset-0 flex justify-center items-center bg-white/70 select-none text-primary-darker"
    x-show="isLoading"
    x-cloak
    x-transition.opacity.duration.200ms
>
    <div class="flex items-center">
        <?= $hyvaicons->renderHtml('loader', '', 40, 40, ['aria-hidden' => 'true']); ?>
    </div>
</div>
