<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 * @var Escaper $escaper
 * @var ViewModelRegistry $viewModels
 */
?>

<script>
    function initProductAddToCart() {
        'use strict';

        return {
            isLoading: false,
            eventListeners: {
                ['@submit.prevent'](event) {
                    this.onFormSubmit(event);
                },
                ['@private-content-loaded.window'](event) {
                    this.onPrivateContentLoaded.call(this, event);
                }
            },

            onFormSubmit(event) {
                event.preventDefault();

                this.validate()
                    .then(() => {
                        // all fields validated
                        this.addToCart.call(this, event.target);
                    })
                    .catch((invalid) => {
                        if (invalid.length > 0) {
                            invalid[0].focus();
                        }
                    });
            },

            addToCart(form) {
                const formData = new FormData(form);
                const data = new URLSearchParams(formData);

                this.isLoading = true;

                return fetch(form.action, {
                    method: 'POST',
                    body: data,
                    headers: {
                        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
                        'X-Requested-With': 'XMLHttpRequest'
                    }
                }).then(response => {
                    if (!response.ok) {
                        return form.submit();
                    }

                    return response.json();
                }).then(data => {
                    if (data.backUrl) {
                        form.submit();

                        return;
                    }

                    window.dispatchEvent(new CustomEvent('reload-customer-section-data'));

                    const productFormData = {
                        productId: formData.get("product"),
                        options: {}
                    }

                    for (const formEntry of formData.entries()) {
                        if (!formEntry[0].startsWith('super_attribute')) continue;
                        const formEntryOption = {[formEntry[0].match(/\[(\d+)\]/)[1]]: formEntry[1]};
                        productFormData.options = {...productFormData.options, ...formEntryOption};
                    }

                    window.dispatchEvent(new CustomEvent('open-ajax-cart', {detail: productFormData}));
                }).catch(error => {
                    console.error(error);
                });
            },

            onPrivateContentLoaded(event) {
                if (this.isLoading === false) {
                    return;
                }

                const sectionData = event.detail.data;

                if (sectionData.cart) {
                    this.isLoading = false;
                }
            }
        }
    }
</script>
