<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer\LoginButton;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\ReCaptcha;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Customer\Block\Account\Customer;
use Magento\Framework\Escaper;
use SR\CustomerOtpAuth\ViewModel\OtpAuthForm;
use SR\CustomerOtpAuth\ViewModel\OtpAuthPopup;

/** @var Escaper $escaper */
/** @var Customer $block */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */
/** @var ReCaptcha $recaptcha */

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaCustomer module
$recaptcha = $block->getData('viewModelRecaptcha');

/** @var LoginButton $loginButtonViewModel */
$loginButtonViewModel = $viewModels->require(LoginButton::class);

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
$isAutocompleteEnabled = $storeConfig->getStoreConfig('customer/password/autocomplete_on_storefront');

$dashboardUrl = $block->getUrl('customer/account');

/** @var OtpAuthPopup $otpAuthPopup */
$otpAuthPopup = $viewModels->require(OtpAuthPopup::class);

/** @var OtpAuthForm $otpAuthPopup */
$otpViewModel = $viewModels->require(OtpAuthForm::class);
$title = $otpViewModel->getOtpTitle();
?>
<script>
    function initAuthentication() {
        return {
            open: false,
            dashboardUrl: '<?= $escaper->escapeJs($dashboardUrl) ?>',
            isCustomerLoggedIn: <?= $otpAuthPopup->isCustomerLoggedIn() ? 'true' : 'false' ?>,
            eventListeners: {
                ['@pageshow.window'](event) {
                    if (event.persisted) {
                        this.open = false;

                        window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                    }
                },
                ['@toggle-authentication.window'](event) {
                    const url = event.detail && event.detail.url,
                        isCheckoutContext = url && url.includes('/checkout');

                    if (this.redirectIfAuthenticated(url)) {
                        return;
                    }

                    this.open = true;

                    this.$dispatch('otp-authentication-popup-opened', {
                        url,
                        otpContext: isCheckoutContext ? 'proceed_to_checkout' : null
                    });
                },
                ['@keydown.window.escape']() {
                    this.open = false
                },
                ['@private-content-loaded.window'](event) {
                    this.onPrivateContentLoaded(event.detail.data);
                }
            },
            init: function () {
                document.addEventListener('click', (event) => {
                    if (event.target.closest('.otp-modal-open')) {
                        event.preventDefault();
                        this.onOtpCustomTrigger();
                    }
                });
            },
            close() {
                this.open = false;
            },
            onPrivateContentLoaded: function (data) {
                this.isCustomerLoggedIn = data.customer && data.customer.firstname;
            },
            redirectIfAuthenticated: function (url) {
                if (this.isCustomerLoggedIn && url) {
                    window.location.href = url;

                    return true;
                }
            },
            onOtpCustomTrigger: function () {
                if (this.isCustomerLoggedIn) {
                    window.location = this.dashboardUrl;
                } else {
                    window.dispatchEvent(new Event('toggle-authentication'));
                }
            }
        }
    }

    window.addEventListener('alpine:init', () => Alpine.data('initAuthentication', initAuthentication), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<?php if ($otpAuthPopup->isCustomerLoggedIn()): ?>
    <div id="authentication-popup"
         x-data="initAuthentication()"
         x-bind="eventListeners"
         hidden
    ></div>
<?php else: ?>
    <dialog
        id="authentication-popup"
        aria-labelledby="authentication-popup-title"
        class="w-[505px] h-full max-h-full me-0 open:flex flex-col transition ease-out duration-300 motion-reduce:duration-0 rounded-e-none"
        x-data="initAuthentication"
        x-bind="eventListeners"
        x-show="open"
        x-htmldialog="close"
        closeby="any"
        x-transition:enter="transition ease-in-out duration-500"
        x-transition:enter-start="translate-x-full rtl:-translate-x-full"
        x-transition:enter-end="translate-x-0"
        x-transition:leave="transition ease-in-out duration-300"
        x-transition:leave-start="translate-x-0"
        x-transition:leave-end="translate-x-full rtl:-translate-x-full"
    >
        <div class="flex gap-2 justify-between items-center pb-1">
            <p id="authentication-popup-title" class="flex items-center">
                <strong class="text-2xl"><?= $escaper->escapeHtml(__($title)) ?></strong>
            </p>
            <button
                type="button"
                class="btn bg-transparent border-transparent p-2"
                @click="close"
                aria-label="<?= $escaper->escapeHtmlAttr('Close panel') ?>"
            >
                <?= $lucideIcons->xHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
            </button>
        </div>
        <div class="flex flex-col h-full overflow-y-auto bg-white">
            <?= $block->getChildHtml('otp_auth_form') ?>
        </div>
    </dialog>
<?php endif; ?>
