<?php
/**
 * Copyright © 2025 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Catalog\Block\Product\ListProduct;
use Magento\Catalog\Block\Product\ReviewRendererInterface;

/** @var ListProduct $block */
/** @var ViewModelRegistry $viewModels */

$productViewModel    = $viewModels->require(ProductPage::class);
$productListItemViewModel = $viewModels->require(ProductListItem::class);

?>
<?php if ($block->getProductCollection() && $block->getProductCollection()->getSize()): ?>
    <?php
    $type = 'widget-product-carousel';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();
    $templateType = ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="glider-contain product-items <?= /* @noEscape */ $type ?>">
        <?php foreach ($items as $item): ?>
            <?= $productListItemViewModel->getItemHtml($item, $block, $mode, $templateType, $image, $description) ?>
        <?php endforeach ?>
        <?= $block->getBlockHtml('pagebuilder.carousel.nav') ?>
    </div>
<?php endif ?>
