<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Contact\Block\ContactForm;
use Magento\Contact\Helper\Data as ContactHelper;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\ReCaptcha;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var ContactForm $block */
/** @var Escaper $escaper */
/** @var ReCaptcha $recaptcha|null */

$formId = 'contact';
/** @var ContactHelper $contactHelper */
$contactHelper = $this->helper(ContactHelper::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that would break the dependency
// on the Magento_ReCaptchaContact module
$recaptcha = $block->getData('viewModelRecaptcha');
?>

<?= $block->getChildHtml('form.additional.before') ?>

<div class="justify-center mx-auto lg:w-1/2 md:w-2/3">
    <?= $block->getChildHtml('form.additional.top') ?>
    <form class="form contact w-full"
          action="<?= $escaper->escapeUrl($block->getFormAction()) ?>"
          id="<?= $escaper->escapeHtmlAttr($formId) ?>"
          method="post"
          x-data="initContactForm()"
          @submit.prevent="submitForm()"
    >

        <fieldset class="">
            <div class="flex flex-col md:flex-row md:flex-wrap -m-2">
                <div class="field name required floating-labels p-2 w-full md:w-1/2">
                    <div class="control">
                        <input name="name" id="name" required title="<?= $escaper->escapeHtmlAttr(__('Full Name')) ?>"
                               value="<?= $escaper->escapeHtmlAttr(
                                   $contactHelper->getPostValue('name')
                                       ?: $contactHelper->getUserName()
                               ) ?>"
                               class="form-input peer"
                               type="text"
                               placeholder="">
                        <label for="name" class="label floating-labels-label">
                            <?= $escaper->escapeHtml(__('Full Name')) ?>
                        </label>
                    </div>
                </div>
                <div class="field email required floating-labels p-2 w-full md:w-1/2">
                    <div class="control">
                        <input name="email" id="email" required title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                               value="<?= $escaper->escapeHtmlAttr(
                                   $contactHelper->getPostValue('email')
                                       ?: $contactHelper->getUserEmail()
                               ) ?>"
                               class="form-input peer"
                               placeholder=""
                               type="email">
                        <label for="email" class="label floating-labels-label">
                            <?= $escaper->escapeHtml(__('Email')) ?>
                        </label>
                    </div>
                </div>
                <div class="field telephone floating-labels p-2 w-full md:w-1/2">
                    <div class="control">
                        <input name="telephone" id="telephone"
                               title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
                               value="<?= $escaper->escapeHtmlAttr(
                                   $contactHelper->getPostValue('telephone')
                               ) ?>"
                               class="form-input peer"
                               placeholder=""
                               type="text">
                        <label for="telephone" class="label floating-labels-label">
                            <?= $escaper->escapeHtml(__('Phone Number')) ?>
                        </label>
                    </div>
                </div>
                <div class="field comment required floating-labels p-2 w-full">
                    <div class="control">
                        <textarea name="comment" id="comment" required
                                  title="<?= $escaper->escapeHtmlAttr(__('Your Message')) ?>"
                                  placeholder=""
                                  class="form-input peer h-48" cols="5" rows="3"><?= $escaper->escapeHtml(
                                      $contactHelper->getPostValue('comment')
                                  ) ?></textarea>
                        <label for="comment" class="label floating-labels-label">
                            <?= $escaper->escapeHtml(__('Your Message')) ?>
                        </label>
                    </div>
                </div>
            </div>
            <?= $block->getChildHtml('form.additional.info') ?>
            <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>
        </fieldset>
        <div class="w-full mt-4">
            <?= $block->getBlockHtml('formkey') ?>
            <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Send')) ?>" class="btn btn-primary">
                <span><?= $escaper->escapeHtml(__('Send')) ?></span>
            </button>
        </div>
        <div class="w-full">
            <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>
        </div>
    </form>
    <?= $block->getChildHtml('form.additional.bottom') ?>
</div>

<?= $block->getChildHtml('form.additional.after') ?>

<script>
    function initContactForm() {
        return {
            errors: 0,
            hasCaptchaToken: 0,
            submitForm() {
                // Do not rename $form, the variable is expected to be declared in the recaptcha output
                const $form = document.querySelector('#<?= $escaper->escapeJs($formId) ?>');
                <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>

                if (this.errors === 0) {
                    $form.submit();
                }
            }
        }
    }
</script>
