<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Snowdog\Menu\Block\Menu;

/** @var Escaper $escaper */
/** @var Menu $block */
/** @var ViewModelRegistry $viewModels */
/** @var LucideIcons $lucideIcons */

$lucideIcons = $viewModels->require(LucideIcons::class);

$menu = $block->getMenu();
$uniqueId = '_' . uniqid();
?>

<?php if ($menu): ?>
    <script>
        'use strict';

        const initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?> = () => ({
            open: false,
            openMenu(event) {
                this.open = true
                this.$nextTick(() => hyva.trapFocus(this.$refs['menu-dialog']))
                // Prevent from body scrolling while mobile menu opened
                document.body.classList.add('fixed', 'w-full')
            },
            close(event) {
                event && event.stopPropagation()
                document.body.classList.remove('fixed', 'w-full')
                this.open = false
                this.$nextTick(() => this.$refs['open-menu-button'].focus() || hyva.releaseFocus())
            },
            toggleSubmenu(index) {
                this[index] = !this[index]

                if (this[index]) {
                    const focusableElements = 'button:not([disabled]), a[href]:not([tabindex="-1"]), [tabindex]:not([tabindex="-1"])'
                    this.$nextTick(() => {
                        this.$refs['submenu-' + index]?.querySelector(focusableElements)?.focus()
                    })
                }
            },
        })
    </script>
    <nav
            class="
            <?= $escaper->escapeHtmlAttr($menu->getCssClass()) ?>
            snowdog-topmenu-mobile z-20 order-2 text-slate-950 sm:order-1 navigation lg:hidden w-10 text-center
        "
            x-data="initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?>()"
            @keydown.escape="open && close"
            @click.outside="open && close"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>"
            role="navigation"
    >
        <button x-ref="open-menu-button"
                @click="openMenu"
                type="button"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Open menu')) ?>"
                :aria-expanded="open"
                aria-haspopup="menu"
        >
            <?= $lucideIcons->renderHtml('menu', '', 24, 24, ['aria-hidden' => 'true']) ?>
        </button>
        <dialog
                id="mobile-menu-popup"
                aria-labelledby="mobile-menu-popup-title"
                class="w-[505px] h-full max-h-full me-0 open:flex flex-col transition ease-out duration-300 motion-reduce:duration-0 rounded-e-none"
                x-show="open"
                x-htmldialog="close"
                closeby="any"
                x-transition:enter="transition ease-in-out duration-500"
                x-transition:enter-start="translate-x-full rtl:-translate-x-full"
                x-transition:enter-end="translate-x-0"
                x-transition:leave="transition ease-in-out duration-300"
                x-transition:leave-start="translate-x-0"
                x-transition:leave-end="translate-x-full rtl:-translate-x-full"
        >
            <div class="flex gap-2 justify-between items-center pb-1">
                <p id="mobile-menu-popup-title" class="sr-only flex items-center">
                    <strong class="text-2xl"><?= $escaper->escapeHtml(__('Main Menu')) ?></strong>
                </p>
                <button
                        type="button"
                        class="btn bg-transparent border-transparent p-2"
                        @click="close"
                        aria-label="<?= $escaper->escapeHtmlAttr('Close panel') ?>"
                >
                    <?= $lucideIcons->xHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
                </button>
            </div>
            <div class="flex flex-col h-full overflow-y-auto bg-white text-start">
                <ul class="mb-1 divide-y divide-container">
                    <?php foreach ($block->getNodes() as $node): ?>
                        <?php
                        $childrenLevel = $node->getLevel() + 1;
                        $children = $block->getNodes($childrenLevel, $node);
                        $node->setIsParent((bool)$children);
                        $indexId = 'node' . $node->getId();
                        $title = $node->getTitle();
                        $nodeType = $node->getType();
                        $nodeClasses = $node->getClasses();
                        ?>
                        <li x-data="{'<?= /* @noEscape */ (string) $indexId ?>': false }"
                            class="<?= /* @noEscape */ (string) $nodeType === 'wrapper' ? $escaper->escapeHtmlAttr($nodeClasses) : '' ?>""
                        >
                        <?php if ($node->getIsParent() && !$node->getIsViewAllLink()): ?>
                            <?php
                            $image = $node->getImage();
                            $imageUrl = $image ? $block->getBaseUrl() . 'media/snowdog/menu/node/' . $image : '';
                            $imageAltText = $node->getImageAltText();
                            $imageWidth = $node->getImageWidth();
                            $imageHeight = $node->getImageHeight();
                            ?>
                            <button
                                    class="flex items-center w-full px-8 py-4"
                                    @click="toggleSubmenu('<?= /* @noEscape */ (string) $indexId ?>')"
                                    aria-label="<?= $escaper->escapeHtmlAttr(__('Toggle submenu for %1', $title)) ?>"
                                    :aria-expanded="<?= /* @noEscape */ (string) $indexId ?> === true"
                                    type="button"
                            >
                                <?php if ($image): ?>
                                    <img class="me-2"
                                         src="<?= $escaper->escapeUrl($imageUrl) ?>"
                                         alt="<?= $escaper->escapeHtmlAttr($imageAltText) ?>"
                                         loading="lazy"
                                         width="<?= $escaper->escapeHtmlAttr($imageWidth) ?>"
                                         height="<?= $escaper->escapeHtmlAttr($imageHeight) ?>"
                                    />
                                <?php endif; ?>
                                <span>
                                        <?= $escaper->escapeHtml($title) ?>
                                    </span>
                                <div class="ms-auto transition-transform"
                                     :class="{'rotate-180' : <?= /* @noEscape */ (string) $indexId ?> === true}"
                                >
                                    <?= $lucideIcons->renderHtml('chevron-down', 'text-gray-500', 20, 20, ['aria-hidden' => 'true']); ?>
                                </div>
                            </button>
                            <?= /* @noEscape */ $block->renderSubmenu($children, $node, $childrenLevel) ?>
                        <?php else: ?>
                            <div class="group">
                                <?= /* @noEscape */ $block->renderMenuNode($node) ?>
                            </div>
                        <?php endif; ?>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
        </dialog>
    </nav>
<?php endif; ?>
