<?php
/**
 * Copyright © 2026 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 * @var Escaper $escaper
 */
?>

<script>
    window.addEventListener('pageshow', (event) => {
        if (event.persisted) {
            if (typeof window.dispatchEvent === 'function') {
                window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
            }
        }
    });
</script>
